/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.api;

import com.logsentinel.ApiException;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiApplicationRuleMappingApi
 */
@Ignore
public class ApiApplicationRuleMappingApiTest {

    private final ApiApplicationRuleMappingApi api = new ApiApplicationRuleMappingApi();

    
    /**
     * getRulesByApplication
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRulesByApplicationTest() throws ApiException {
        UUID applicationId = null;
        List<UUID> response = api.getRulesByApplication(applicationId);

        // TODO: test validations
    }
    
}
