/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.api;

import com.logsentinel.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AssetsApi
 */
@Ignore
public class AssetsApiTest {

    private final AssetsApi api = new AssetsApi();

    
    /**
     * Check asset
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void assetExistsTest() throws ApiException {
        String ip = null;
        Integer port = null;
        String protocol = null;
        Boolean response = api.assetExists(ip, port, protocol);

        // TODO: test validations
    }
    
    /**
     * Insert asset
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insertAssetTest() throws ApiException {
        String ip = null;
        Integer port = null;
        String protocol = null;
        String serviceName = null;
        Integer riskLevel = null;
        String sourceCategory = null;
        api.insertAsset(ip, port, protocol, serviceName, riskLevel, sourceCategory);

        // TODO: test validations
    }
    
}
