/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.api;

import com.logsentinel.ApiException;
import com.logsentinel.model.DeferredResultOfAutomatedResponse;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AutomatedResponseApi
 */
@Ignore
public class AutomatedResponseApiTest {

    private final AutomatedResponseApi api = new AutomatedResponseApi();

    
    /**
     * connect
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void connectTest() throws ApiException {
        UUID collectorId = null;
        DeferredResultOfAutomatedResponse response = api.connect(collectorId);

        // TODO: test validations
    }
    
}
