/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.api;

import com.logsentinel.ApiException;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CollectorApi
 */
@Ignore
public class CollectorApiTest {

    private final CollectorApi api = new CollectorApi();

    
    /**
     * Invoked during Collector&#39;s operation. Publish statistics for (some of) collector&#39;s Agent(s)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendStatisticsTest() throws ApiException {
        UUID collectorId = null;
        api.sendStatistics(collectorId);

        // TODO: test validations
    }
    
    /**
     * Invoked during Collector instance startup. Publish all configured Agent(s)together with their respective dataSourceId(s)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sysInitTest() throws ApiException {
        UUID collectorId = null;
        String info0AdditionalMessage = null;
        String info0ConnectorId = null;
        String info0ConnectorName = null;
        List<String> info0DataSourceIds = null;
        Boolean info0NewlyCreated = null;
        String info0Status = null;
        api.sysInit(collectorId, info0AdditionalMessage, info0ConnectorId, info0ConnectorName, info0DataSourceIds, info0NewlyCreated, info0Status);

        // TODO: test validations
    }
    
    /**
     * Invoked during Collector&#39;s operation. Publish current status of (some of) collector&#39;s Agent(s)(no dataSourceIds included)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateStatusTest() throws ApiException {
        UUID collectorId = null;
        String info0AdditionalMessage = null;
        String info0ConnectorId = null;
        String info0ConnectorName = null;
        List<String> info0DataSourceIds = null;
        Boolean info0NewlyCreated = null;
        String info0Status = null;
        api.updateStatus(collectorId, info0AdditionalMessage, info0ConnectorId, info0ConnectorName, info0DataSourceIds, info0NewlyCreated, info0Status);

        // TODO: test validations
    }
    
}
