/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.api;

import com.logsentinel.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LeakedCredentialsControllerApi
 */
@Ignore
public class LeakedCredentialsControllerApiTest {

    private final LeakedCredentialsControllerApi api = new LeakedCredentialsControllerApi();

    
    /**
     * Insert emails
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insertEmailsTest() throws ApiException {
        List<String> emails = null;
        api.insertEmails(emails);

        // TODO: test validations
    }
    
}
