/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.api;

import com.logsentinel.ApiException;
import com.logsentinel.model.KubernetesAuditLogRequest;
import com.logsentinel.model.LogResponse;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LogMiscellaneousApi
 */
@Ignore
public class LogMiscellaneousApiTest {

    private final LogMiscellaneousApi api = new LogMiscellaneousApi();

    
    /**
     * Consume kubernetes audit log
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logKubernetesEventTest() throws ApiException {
        UUID applicationId = null;
        KubernetesAuditLogRequest request = null;
        api.logKubernetesEvent(applicationId, request);

        // TODO: test validations
    }
    
    /**
     * Logs a Provenance document
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logProvenanceTest() throws ApiException {
        String applicationId = null;
        String provenanceDocument = null;
        LogResponse response = api.logProvenance(applicationId, provenanceDocument);

        // TODO: test validations
    }
    
}
