/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.api;

import com.logsentinel.ApiException;
import com.logsentinel.model.APICredentialsOrganization;
import com.logsentinel.model.RegistrationResponse;
import java.util.UUID;
import com.logsentinel.model.UserRegistrationRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PartnersApi
 */
@Ignore
public class PartnersApiTest {

    private final PartnersApi api = new PartnersApi();

    
    /**
     * Cancels organization by Id and deletes all users
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelOrganizationTest() throws ApiException {
        UUID organizationId = null;
        api.cancelOrganization(organizationId);

        // TODO: test validations
    }
    
    /**
     * Fetch all organizations
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchAllOrganizationsTest() throws ApiException {
        List<UUID> response = api.fetchAllOrganizations();

        // TODO: test validations
    }
    
    /**
     * API credentials per organization from organizations owned by partner
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getApiCredentialsTest() throws ApiException {
        Map<String, List<APICredentialsOrganization>> response = api.getApiCredentials();

        // TODO: test validations
    }
    
    /**
     * Register a user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerUserTest() throws ApiException {
        UserRegistrationRequest request = null;
        RegistrationResponse response = api.registerUser(request);

        // TODO: test validations
    }
    
}
