/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.api;

import com.logsentinel.ApiException;
import com.logsentinel.model.Bundle;
import com.logsentinel.model.TaxiiCollections;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ThreatIntelligenceApi
 */
@Ignore
public class ThreatIntelligenceApiTest {

    private final ThreatIntelligenceApi api = new ThreatIntelligenceApi();

    
    /**
     * getCollectionObjects
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCollectionObjectsTest() throws ApiException {
        String id = null;
        Bundle response = api.getCollectionObjects(id);

        // TODO: test validations
    }
    
    /**
     * getCollections
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCollectionsTest() throws ApiException {
        TaxiiCollections response = api.getCollections();

        // TODO: test validations
    }
    
}
