/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import org.javers.core.diff.Diff;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModelProperty;

/**
 * ActionData
 */

public class ActionData<T> {
  @JsonProperty("action")
  private String action = null;

  @JsonProperty("details")
  private T details = null;

  @JsonProperty("entityId")
  private String entityId = null;

  @JsonProperty("entityType")
  private String entityType = null;
  
  @JsonIgnore
  private byte[] encryptionKey;

  @JsonIgnore
  private Diff diffDetails;
  
  @JsonIgnore
  private boolean binaryContent;
  
  @JsonIgnore
  private Map<String, String> additionalParams = new HashMap<>();
  
  /**
   * Gets or Sets entryType
   */
  public enum EntryTypeEnum {
    BUSINESS_LOGIC_ENTRY("BUSINESS_LOGIC_ENTRY"),
    
    DATABASE_QUERY("DATABASE_QUERY"),
    
    SYSTEM_EVENT("SYSTEM_EVENT"),
    
    NETWORK_EVENT("NETWORK_EVENT"),
    
    ANONYMIZED_ENTRY("ANONYMIZED_ENTRY"),
    
    SPECIALIZED_BUSINESS_LOGIC_ENTRY("SPECIALIZED_BUSINESS_LOGIC_ENTRY"),
    
    DOCUMENT("DOCUMENT");

    private String value;

    EntryTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EntryTypeEnum fromValue(String text) {
      for (EntryTypeEnum b : EntryTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("entryType")
  private EntryTypeEnum entryType = null;

  public ActionData<T> action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @ApiModelProperty(value = "")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public ActionData<T> details(T details) {
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @ApiModelProperty(value = "")
  public T getDetails() {
    return details;
  }

  public void setDetails(T details) {
    this.details = details;
  }

  public ActionData<T> entityId(String entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * Get entityId
   * @return entityId
  **/
  @ApiModelProperty(value = "")
  public String getEntityId() {
    return entityId;
  }

  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }

  public ActionData<T> entityType(String entityType) {
    this.entityType = entityType;
    return this;
  }

   /**
   * Get entityType
   * @return entityType
  **/
  @ApiModelProperty(value = "")
  public String getEntityType() {
    return entityType;
  }

  public void setEntityType(String entityType) {
    this.entityType = entityType;
  }

  public ActionData<T> entryType(EntryTypeEnum entryType) {
    this.entryType = entryType;
    return this;
  }

   /**
   * Get entryType
   * @return entryType
  **/
  @ApiModelProperty(value = "")
  public EntryTypeEnum getEntryType() {
    return entryType;
  }

  public void setEntryType(EntryTypeEnum entryType) {
    this.entryType = entryType;
  }

  public byte[] getEncryptionKey() {
    return encryptionKey;
  }

  public void setEncryptionKey(byte[] encryptionKey) {
    this.encryptionKey = encryptionKey;
  }

  
  public Diff getDiffDetails() {
    return diffDetails;
  }
    
  public void setDiffDetails(Diff diffDetails) {
    this.diffDetails = diffDetails;
  }
  
  public boolean isBinaryContent() {
    return binaryContent;
  }

  public void setBinaryContent(boolean binaryContent) {
    this.binaryContent = binaryContent;
  }
  
  public ActionData<T> binaryContent(boolean binaryContent) {
      setBinaryContent(binaryContent);
      return this;
  }


  /**
   * Gets the additional params
   * @return map of params
   */
  public Map<String, String> getAdditionalParams() {
      return additionalParams;
  }
  
  /**
   * Adds an additional param
   * @param name the param name
   * @param value the param value
   */
  public ActionData<?> addAdditionalParam(String name, String value) {
     additionalParams.put(name, value);
     return this;
  }
  
@Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionData<T> actionData = (ActionData<T>) o;
    return Objects.equals(this.action, actionData.action) &&
        Objects.equals(this.details, actionData.details) &&
        Objects.equals(this.entityId, actionData.entityId) &&
        Objects.equals(this.entityType, actionData.entityType) &&
        Objects.equals(this.entryType, actionData.entryType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, details, entityId, entityType, entryType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionData {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("    entryType: ").append(toIndentedString(entryType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

