/*
 * RESTful API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.logsentinel.model.SuppressionSettings;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * AlertRule
 */

public class AlertRule {
  @JsonProperty("aggregationPeriod")
  private String aggregationPeriod = null;

  /**
   * Gets or Sets aggregationType
   */
  public enum AggregationTypeEnum {
    COUNT("COUNT"),
    
    AVG("AVG"),
    
    SUM("SUM"),
    
    MAX("MAX"),
    
    MIN("MIN");

    private String value;

    AggregationTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AggregationTypeEnum fromValue(String text) {
      for (AggregationTypeEnum b : AggregationTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("aggregationType")
  private AggregationTypeEnum aggregationType = null;

  @JsonProperty("alertDestinationIds")
  private List<UUID> alertDestinationIds = null;

  @JsonProperty("applicationIds")
  private List<UUID> applicationIds = null;

  @JsonProperty("automaticCase")
  private Boolean automaticCase = null;

  @JsonProperty("created")
  private LocalDateTime created = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("displayPreviousAlertsSearchDays")
  private Integer displayPreviousAlertsSearchDays = null;

  @JsonProperty("enabled")
  private Boolean enabled = null;

  @JsonProperty("filterBy")
  private String filterBy = null;

  @JsonProperty("groupByField")
  private String groupByField = null;

  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("insideWorkingHours")
  private Boolean insideWorkingHours = null;

  @JsonProperty("joinAlertsPeriod")
  private Integer joinAlertsPeriod = null;

  /**
   * Gets or Sets joinAlertsPeriodType
   */
  public enum JoinAlertsPeriodTypeEnum {
    SECOND("SECOND"),
    
    MINUTE("MINUTE"),
    
    HOUR("HOUR"),
    
    DAY("DAY"),
    
    WEEK("WEEK"),
    
    MONTH("MONTH"),
    
    YEAR("YEAR");

    private String value;

    JoinAlertsPeriodTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static JoinAlertsPeriodTypeEnum fromValue(String text) {
      for (JoinAlertsPeriodTypeEnum b : JoinAlertsPeriodTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("joinAlertsPeriodType")
  private JoinAlertsPeriodTypeEnum joinAlertsPeriodType = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("organizationId")
  private UUID organizationId = null;

  @JsonProperty("resultDisplayAggregationField")
  private String resultDisplayAggregationField = null;

  @JsonProperty("riskLevel")
  private Integer riskLevel = null;

  /**
   * Gets or Sets ruleType
   */
  public enum RuleTypeEnum {
    REGULAR("REGULAR"),
    
    HEALTHCHECK("HEALTHCHECK"),
    
    BEHAVIOR("BEHAVIOR");

    private String value;

    RuleTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RuleTypeEnum fromValue(String text) {
      for (RuleTypeEnum b : RuleTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("ruleType")
  private RuleTypeEnum ruleType = null;

  @JsonProperty("searchPeriod")
  private String searchPeriod = null;

  @JsonProperty("suppressionSettings")
  private SuppressionSettings suppressionSettings = null;

  @JsonProperty("tags")
  private List<String> tags = null;

  /**
   * Gets or Sets thresholdType
   */
  public enum ThresholdTypeEnum {
    ABOVE("ABOVE"),
    
    BELOW("BELOW"),
    
    BOTH("BOTH");

    private String value;

    ThresholdTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ThresholdTypeEnum fromValue(String text) {
      for (ThresholdTypeEnum b : ThresholdTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("thresholdType")
  private ThresholdTypeEnum thresholdType = null;

  @JsonProperty("thresholdValue")
  private Double thresholdValue = null;

  @JsonProperty("topFieldsCount")
  private Integer topFieldsCount = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    ST_DEV("ST_DEV"),
    
    MEAN("MEAN"),
    
    FIXED("FIXED");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("updated")
  private LocalDateTime updated = null;

  public AlertRule aggregationPeriod(String aggregationPeriod) {
    this.aggregationPeriod = aggregationPeriod;
    return this;
  }

   /**
   * Get aggregationPeriod
   * @return aggregationPeriod
  **/
  @ApiModelProperty(value = "")
  public String getAggregationPeriod() {
    return aggregationPeriod;
  }

  public void setAggregationPeriod(String aggregationPeriod) {
    this.aggregationPeriod = aggregationPeriod;
  }

  public AlertRule aggregationType(AggregationTypeEnum aggregationType) {
    this.aggregationType = aggregationType;
    return this;
  }

   /**
   * Get aggregationType
   * @return aggregationType
  **/
  @ApiModelProperty(value = "")
  public AggregationTypeEnum getAggregationType() {
    return aggregationType;
  }

  public void setAggregationType(AggregationTypeEnum aggregationType) {
    this.aggregationType = aggregationType;
  }

  public AlertRule alertDestinationIds(List<UUID> alertDestinationIds) {
    this.alertDestinationIds = alertDestinationIds;
    return this;
  }

  public AlertRule addAlertDestinationIdsItem(UUID alertDestinationIdsItem) {
    if (this.alertDestinationIds == null) {
      this.alertDestinationIds = new ArrayList<>();
    }
    this.alertDestinationIds.add(alertDestinationIdsItem);
    return this;
  }

   /**
   * Get alertDestinationIds
   * @return alertDestinationIds
  **/
  @ApiModelProperty(value = "")
  public List<UUID> getAlertDestinationIds() {
    return alertDestinationIds;
  }

  public void setAlertDestinationIds(List<UUID> alertDestinationIds) {
    this.alertDestinationIds = alertDestinationIds;
  }

  public AlertRule applicationIds(List<UUID> applicationIds) {
    this.applicationIds = applicationIds;
    return this;
  }

  public AlertRule addApplicationIdsItem(UUID applicationIdsItem) {
    if (this.applicationIds == null) {
      this.applicationIds = new ArrayList<>();
    }
    this.applicationIds.add(applicationIdsItem);
    return this;
  }

   /**
   * Get applicationIds
   * @return applicationIds
  **/
  @ApiModelProperty(value = "")
  public List<UUID> getApplicationIds() {
    return applicationIds;
  }

  public void setApplicationIds(List<UUID> applicationIds) {
    this.applicationIds = applicationIds;
  }

  public AlertRule automaticCase(Boolean automaticCase) {
    this.automaticCase = automaticCase;
    return this;
  }

   /**
   * Get automaticCase
   * @return automaticCase
  **/
  @ApiModelProperty(value = "")
  public Boolean isAutomaticCase() {
    return automaticCase;
  }

  public void setAutomaticCase(Boolean automaticCase) {
    this.automaticCase = automaticCase;
  }
  
  public AlertRule created(LocalDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getCreated() {
    return created;
  }

  public void setCreated(LocalDateTime created) {
    this.created = created;
  }

  public AlertRule description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AlertRule displayPreviousAlertsSearchDays(Integer displayPreviousAlertsSearchDays) {
    this.displayPreviousAlertsSearchDays = displayPreviousAlertsSearchDays;
    return this;
  }

   /**
   * Get displayPreviousAlertsSearchDays
   * @return displayPreviousAlertsSearchDays
  **/
  @ApiModelProperty(value = "")
  public Integer getDisplayPreviousAlertsSearchDays() {
    return displayPreviousAlertsSearchDays;
  }

  public void setDisplayPreviousAlertsSearchDays(Integer displayPreviousAlertsSearchDays) {
    this.displayPreviousAlertsSearchDays = displayPreviousAlertsSearchDays;
  }

  public AlertRule enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public AlertRule filterBy(String filterBy) {
    this.filterBy = filterBy;
    return this;
  }

   /**
   * Get filterBy
   * @return filterBy
  **/
  @ApiModelProperty(value = "")
  public String getFilterBy() {
    return filterBy;
  }

  public void setFilterBy(String filterBy) {
    this.filterBy = filterBy;
  }

  public AlertRule groupByField(String groupByField) {
    this.groupByField = groupByField;
    return this;
  }

   /**
   * Get groupByField
   * @return groupByField
  **/
  @ApiModelProperty(value = "")
  public String getGroupByField() {
    return groupByField;
  }

  public void setGroupByField(String groupByField) {
    this.groupByField = groupByField;
  }

  public AlertRule id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public AlertRule insideWorkingHours(Boolean insideWorkingHours) {
    this.insideWorkingHours = insideWorkingHours;
    return this;
  }

   /**
   * Get insideWorkingHours
   * @return insideWorkingHours
  **/
  @ApiModelProperty(value = "")
  public Boolean isInsideWorkingHours() {
    return insideWorkingHours;
  }

  public void setInsideWorkingHours(Boolean insideWorkingHours) {
    this.insideWorkingHours = insideWorkingHours;
  }

  public AlertRule joinAlertsPeriod(Integer joinAlertsPeriod) {
    this.joinAlertsPeriod = joinAlertsPeriod;
    return this;
  }

   /**
   * Get joinAlertsPeriod
   * @return joinAlertsPeriod
  **/
  @ApiModelProperty(value = "")
  public Integer getJoinAlertsPeriod() {
    return joinAlertsPeriod;
  }

  public void setJoinAlertsPeriod(Integer joinAlertsPeriod) {
    this.joinAlertsPeriod = joinAlertsPeriod;
  }

  public AlertRule joinAlertsPeriodType(JoinAlertsPeriodTypeEnum joinAlertsPeriodType) {
    this.joinAlertsPeriodType = joinAlertsPeriodType;
    return this;
  }

   /**
   * Get joinAlertsPeriodType
   * @return joinAlertsPeriodType
  **/
  @ApiModelProperty(value = "")
  public JoinAlertsPeriodTypeEnum getJoinAlertsPeriodType() {
    return joinAlertsPeriodType;
  }

  public void setJoinAlertsPeriodType(JoinAlertsPeriodTypeEnum joinAlertsPeriodType) {
    this.joinAlertsPeriodType = joinAlertsPeriodType;
  }

  public AlertRule name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AlertRule organizationId(UUID organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @ApiModelProperty(value = "")
  public UUID getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(UUID organizationId) {
    this.organizationId = organizationId;
  }

  public AlertRule resultDisplayAggregationField(String resultDisplayAggregationField) {
    this.resultDisplayAggregationField = resultDisplayAggregationField;
    return this;
  }

   /**
   * Get resultDisplayAggregationField
   * @return resultDisplayAggregationField
  **/
  @ApiModelProperty(value = "")
  public String getResultDisplayAggregationField() {
    return resultDisplayAggregationField;
  }

  public void setResultDisplayAggregationField(String resultDisplayAggregationField) {
    this.resultDisplayAggregationField = resultDisplayAggregationField;
  }

  public AlertRule riskLevel(Integer riskLevel) {
    this.riskLevel = riskLevel;
    return this;
  }

   /**
   * Get riskLevel
   * @return riskLevel
  **/
  @ApiModelProperty(value = "")
  public Integer getRiskLevel() {
    return riskLevel;
  }

  public void setRiskLevel(Integer riskLevel) {
    this.riskLevel = riskLevel;
  }

  public AlertRule ruleType(RuleTypeEnum ruleType) {
    this.ruleType = ruleType;
    return this;
  }

   /**
   * Get ruleType
   * @return ruleType
  **/
  @ApiModelProperty(value = "")
  public RuleTypeEnum getRuleType() {
    return ruleType;
  }

  public void setRuleType(RuleTypeEnum ruleType) {
    this.ruleType = ruleType;
  }

  public AlertRule searchPeriod(String searchPeriod) {
    this.searchPeriod = searchPeriod;
    return this;
  }

   /**
   * Get searchPeriod
   * @return searchPeriod
  **/
  @ApiModelProperty(value = "")
  public String getSearchPeriod() {
    return searchPeriod;
  }

  public void setSearchPeriod(String searchPeriod) {
    this.searchPeriod = searchPeriod;
  }

  public AlertRule suppressionSettings(SuppressionSettings suppressionSettings) {
    this.suppressionSettings = suppressionSettings;
    return this;
  }

   /**
   * Get suppressionSettings
   * @return suppressionSettings
  **/
  @ApiModelProperty(value = "")
  public SuppressionSettings getSuppressionSettings() {
    return suppressionSettings;
  }

  public void setSuppressionSettings(SuppressionSettings suppressionSettings) {
    this.suppressionSettings = suppressionSettings;
  }

  public AlertRule tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public AlertRule addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public AlertRule thresholdType(ThresholdTypeEnum thresholdType) {
    this.thresholdType = thresholdType;
    return this;
  }

   /**
   * Get thresholdType
   * @return thresholdType
  **/
  @ApiModelProperty(value = "")
  public ThresholdTypeEnum getThresholdType() {
    return thresholdType;
  }

  public void setThresholdType(ThresholdTypeEnum thresholdType) {
    this.thresholdType = thresholdType;
  }

  public AlertRule thresholdValue(Double thresholdValue) {
    this.thresholdValue = thresholdValue;
    return this;
  }

   /**
   * Get thresholdValue
   * @return thresholdValue
  **/
  @ApiModelProperty(value = "")
  public Double getThresholdValue() {
    return thresholdValue;
  }

  public void setThresholdValue(Double thresholdValue) {
    this.thresholdValue = thresholdValue;
  }

  public AlertRule topFieldsCount(Integer topFieldsCount) {
    this.topFieldsCount = topFieldsCount;
    return this;
  }

   /**
   * Get topFieldsCount
   * @return topFieldsCount
  **/
  @ApiModelProperty(value = "")
  public Integer getTopFieldsCount() {
    return topFieldsCount;
  }

  public void setTopFieldsCount(Integer topFieldsCount) {
    this.topFieldsCount = topFieldsCount;
  }

  public AlertRule type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public AlertRule updated(LocalDateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getUpdated() {
    return updated;
  }

  public void setUpdated(LocalDateTime updated) {
    this.updated = updated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlertRule alertRule = (AlertRule) o;
    return Objects.equals(this.aggregationPeriod, alertRule.aggregationPeriod) &&
        Objects.equals(this.aggregationType, alertRule.aggregationType) &&
        Objects.equals(this.alertDestinationIds, alertRule.alertDestinationIds) &&
        Objects.equals(this.applicationIds, alertRule.applicationIds) &&
        Objects.equals(this.automaticCase, alertRule.automaticCase) &&
        Objects.equals(this.created, alertRule.created) &&
        Objects.equals(this.description, alertRule.description) &&
        Objects.equals(this.displayPreviousAlertsSearchDays, alertRule.displayPreviousAlertsSearchDays) &&
        Objects.equals(this.enabled, alertRule.enabled) &&
        Objects.equals(this.filterBy, alertRule.filterBy) &&
        Objects.equals(this.groupByField, alertRule.groupByField) &&
        Objects.equals(this.id, alertRule.id) &&
        Objects.equals(this.insideWorkingHours, alertRule.insideWorkingHours) &&
        Objects.equals(this.joinAlertsPeriod, alertRule.joinAlertsPeriod) &&
        Objects.equals(this.joinAlertsPeriodType, alertRule.joinAlertsPeriodType) &&
        Objects.equals(this.name, alertRule.name) &&
        Objects.equals(this.organizationId, alertRule.organizationId) &&
        Objects.equals(this.resultDisplayAggregationField, alertRule.resultDisplayAggregationField) &&
        Objects.equals(this.riskLevel, alertRule.riskLevel) &&
        Objects.equals(this.ruleType, alertRule.ruleType) &&
        Objects.equals(this.searchPeriod, alertRule.searchPeriod) &&
        Objects.equals(this.suppressionSettings, alertRule.suppressionSettings) &&
        Objects.equals(this.tags, alertRule.tags) &&
        Objects.equals(this.thresholdType, alertRule.thresholdType) &&
        Objects.equals(this.thresholdValue, alertRule.thresholdValue) &&
        Objects.equals(this.topFieldsCount, alertRule.topFieldsCount) &&
        Objects.equals(this.type, alertRule.type) &&
        Objects.equals(this.updated, alertRule.updated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aggregationPeriod, aggregationType, alertDestinationIds, applicationIds, automaticCase, created, description, displayPreviousAlertsSearchDays, enabled, filterBy, groupByField, id, insideWorkingHours, joinAlertsPeriod, joinAlertsPeriodType, name, organizationId, resultDisplayAggregationField, riskLevel, ruleType, searchPeriod, suppressionSettings, tags, thresholdType, thresholdValue, topFieldsCount, type, updated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlertRule {\n");
    
    sb.append("    aggregationPeriod: ").append(toIndentedString(aggregationPeriod)).append("\n");
    sb.append("    aggregationType: ").append(toIndentedString(aggregationType)).append("\n");
    sb.append("    alertDestinationIds: ").append(toIndentedString(alertDestinationIds)).append("\n");
    sb.append("    applicationIds: ").append(toIndentedString(applicationIds)).append("\n");
    sb.append("    automaticCase: ").append(toIndentedString(automaticCase)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayPreviousAlertsSearchDays: ").append(toIndentedString(displayPreviousAlertsSearchDays)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    filterBy: ").append(toIndentedString(filterBy)).append("\n");
    sb.append("    groupByField: ").append(toIndentedString(groupByField)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    insideWorkingHours: ").append(toIndentedString(insideWorkingHours)).append("\n");
    sb.append("    joinAlertsPeriod: ").append(toIndentedString(joinAlertsPeriod)).append("\n");
    sb.append("    joinAlertsPeriodType: ").append(toIndentedString(joinAlertsPeriodType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    resultDisplayAggregationField: ").append(toIndentedString(resultDisplayAggregationField)).append("\n");
    sb.append("    riskLevel: ").append(toIndentedString(riskLevel)).append("\n");
    sb.append("    ruleType: ").append(toIndentedString(ruleType)).append("\n");
    sb.append("    searchPeriod: ").append(toIndentedString(searchPeriod)).append("\n");
    sb.append("    suppressionSettings: ").append(toIndentedString(suppressionSettings)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    thresholdType: ").append(toIndentedString(thresholdType)).append("\n");
    sb.append("    thresholdValue: ").append(toIndentedString(thresholdValue)).append("\n");
    sb.append("    topFieldsCount: ").append(toIndentedString(topFieldsCount)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

