/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * AlertRuleRun
 */

public class AlertRuleRun {
  @JsonProperty("actualValue")
  private Double actualValue = null;

  @JsonProperty("alertRuleId")
  private UUID alertRuleId = null;

  @JsonProperty("alertRuleName")
  private String alertRuleName = null;

  /**
   * Gets or Sets alertType
   */
  public enum AlertTypeEnum {
    STATISTICAL("STATISTICAL"),
    
    CORRELATION("CORRELATION"),
    
    ANOMALY("ANOMALY"),
    
    LOG_LEVEL_BASED("LOG_LEVEL_BASED"),
    
    THREAT_INTEL_MATCH("THREAT_INTEL_MATCH"),
    
    HEALTHCHECK("HEALTHCHECK"),
    
    WEBSITE_STATIC_RESOURCE_CHANGE("WEBSITE_STATIC_RESOURCE_CHANGE");

    private String value;

    AlertTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AlertTypeEnum fromValue(String text) {
      for (AlertTypeEnum b : AlertTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("alertType")
  private AlertTypeEnum alertType = null;

  @JsonProperty("applicationName")
  private String applicationName = null;

  @JsonProperty("created")
  private LocalDateTime created = null;

  @JsonProperty("details")
  private String details = null;

  @JsonProperty("entryIds")
  private List<UUID> entryIds = null;

  @JsonProperty("executionDuration")
  private Long executionDuration = null;

  @JsonProperty("fired")
  private Boolean fired = null;

  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("ioc")
  private List<String> ioc = null;

  @JsonProperty("notified")
  private Boolean notified = null;

  @JsonProperty("organizationId")
  private UUID organizationId = null;

  @JsonProperty("riskLevel")
  private Integer riskLevel = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    NEW_ALERT("NEW_ALERT"),
    
    IN_TRIAGE("IN_TRIAGE"),
    
    CONFIRMED("CONFIRMED"),
    
    RESOLVED("RESOLVED"),
    
    DISMISSED("DISMISSED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("tags")
  private List<String> tags = null;

  @JsonProperty("threshold")
  private Double threshold = null;

  /**
   * Gets or Sets thresholdType
   */
  public enum ThresholdTypeEnum {
    ABOVE("ABOVE"),
    
    BELOW("BELOW"),
    
    BOTH("BOTH");

    private String value;

    ThresholdTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ThresholdTypeEnum fromValue(String text) {
      for (ThresholdTypeEnum b : ThresholdTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("thresholdType")
  private ThresholdTypeEnum thresholdType = null;

  @JsonProperty("triageStartTime")
  private LocalDateTime triageStartTime = null;

  public AlertRuleRun actualValue(Double actualValue) {
    this.actualValue = actualValue;
    return this;
  }

   /**
   * Get actualValue
   * @return actualValue
  **/
  @ApiModelProperty(value = "")
  public Double getActualValue() {
    return actualValue;
  }

  public void setActualValue(Double actualValue) {
    this.actualValue = actualValue;
  }

  public AlertRuleRun alertRuleId(UUID alertRuleId) {
    this.alertRuleId = alertRuleId;
    return this;
  }

   /**
   * Get alertRuleId
   * @return alertRuleId
  **/
  @ApiModelProperty(value = "")
  public UUID getAlertRuleId() {
    return alertRuleId;
  }

  public void setAlertRuleId(UUID alertRuleId) {
    this.alertRuleId = alertRuleId;
  }

  public AlertRuleRun alertRuleName(String alertRuleName) {
    this.alertRuleName = alertRuleName;
    return this;
  }

   /**
   * Get alertRuleName
   * @return alertRuleName
  **/
  @ApiModelProperty(value = "")
  public String getAlertRuleName() {
    return alertRuleName;
  }

  public void setAlertRuleName(String alertRuleName) {
    this.alertRuleName = alertRuleName;
  }

  public AlertRuleRun alertType(AlertTypeEnum alertType) {
    this.alertType = alertType;
    return this;
  }

   /**
   * Get alertType
   * @return alertType
  **/
  @ApiModelProperty(value = "")
  public AlertTypeEnum getAlertType() {
    return alertType;
  }

  public void setAlertType(AlertTypeEnum alertType) {
    this.alertType = alertType;
  }

  public AlertRuleRun applicationName(String applicationName) {
    this.applicationName = applicationName;
    return this;
  }

   /**
   * Get applicationName
   * @return applicationName
  **/
  @ApiModelProperty(value = "")
  public String getApplicationName() {
    return applicationName;
  }

  public void setApplicationName(String applicationName) {
    this.applicationName = applicationName;
  }

  public AlertRuleRun created(LocalDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getCreated() {
    return created;
  }

  public void setCreated(LocalDateTime created) {
    this.created = created;
  }

  public AlertRuleRun details(String details) {
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @ApiModelProperty(value = "")
  public String getDetails() {
    return details;
  }

  public void setDetails(String details) {
    this.details = details;
  }

  public AlertRuleRun entryIds(List<UUID> entryIds) {
    this.entryIds = entryIds;
    return this;
  }

  public AlertRuleRun addEntryIdsItem(UUID entryIdsItem) {
    if (this.entryIds == null) {
      this.entryIds = new ArrayList<>();
    }
    this.entryIds.add(entryIdsItem);
    return this;
  }

   /**
   * Get entryIds
   * @return entryIds
  **/
  @ApiModelProperty(value = "")
  public List<UUID> getEntryIds() {
    return entryIds;
  }

  public void setEntryIds(List<UUID> entryIds) {
    this.entryIds = entryIds;
  }

  public AlertRuleRun executionDuration(Long executionDuration) {
    this.executionDuration = executionDuration;
    return this;
  }

   /**
   * Get executionDuration
   * @return executionDuration
  **/
  @ApiModelProperty(value = "")
  public Long getExecutionDuration() {
    return executionDuration;
  }

  public void setExecutionDuration(Long executionDuration) {
    this.executionDuration = executionDuration;
  }

  public AlertRuleRun fired(Boolean fired) {
    this.fired = fired;
    return this;
  }

   /**
   * Get fired
   * @return fired
  **/
  @ApiModelProperty(value = "")
  public Boolean isFired() {
    return fired;
  }

  public void setFired(Boolean fired) {
    this.fired = fired;
  }

  public AlertRuleRun id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public AlertRuleRun ioc(List<String> ioc) {
    this.ioc = ioc;
    return this;
  }

  public AlertRuleRun addIocItem(String iocItem) {
    if (this.ioc == null) {
      this.ioc = new ArrayList<>();
    }
    this.ioc.add(iocItem);
    return this;
  }

   /**
   * Get ioc
   * @return ioc
  **/
  @ApiModelProperty(value = "")
  public List<String> getIoc() {
    return ioc;
  }

  public void setIoc(List<String> ioc) {
    this.ioc = ioc;
  }

  public AlertRuleRun notified(Boolean notified) {
    this.notified = notified;
    return this;
  }

   /**
   * Get notified
   * @return notified
  **/
  @ApiModelProperty(value = "")
  public Boolean isNotified() {
    return notified;
  }

  public void setNotified(Boolean notified) {
    this.notified = notified;
  }

  public AlertRuleRun organizationId(UUID organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @ApiModelProperty(value = "")
  public UUID getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(UUID organizationId) {
    this.organizationId = organizationId;
  }

  public AlertRuleRun riskLevel(Integer riskLevel) {
    this.riskLevel = riskLevel;
    return this;
  }

   /**
   * Get riskLevel
   * @return riskLevel
  **/
  @ApiModelProperty(value = "")
  public Integer getRiskLevel() {
    return riskLevel;
  }

  public void setRiskLevel(Integer riskLevel) {
    this.riskLevel = riskLevel;
  }

  public AlertRuleRun status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public AlertRuleRun tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public AlertRuleRun addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public AlertRuleRun threshold(Double threshold) {
    this.threshold = threshold;
    return this;
  }

   /**
   * Get threshold
   * @return threshold
  **/
  @ApiModelProperty(value = "")
  public Double getThreshold() {
    return threshold;
  }

  public void setThreshold(Double threshold) {
    this.threshold = threshold;
  }

  public AlertRuleRun thresholdType(ThresholdTypeEnum thresholdType) {
    this.thresholdType = thresholdType;
    return this;
  }

   /**
   * Get thresholdType
   * @return thresholdType
  **/
  @ApiModelProperty(value = "")
  public ThresholdTypeEnum getThresholdType() {
    return thresholdType;
  }

  public void setThresholdType(ThresholdTypeEnum thresholdType) {
    this.thresholdType = thresholdType;
  }

  public AlertRuleRun triageStartTime(LocalDateTime triageStartTime) {
    this.triageStartTime = triageStartTime;
    return this;
  }

   /**
   * Get triageStartTime
   * @return triageStartTime
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getTriageStartTime() {
    return triageStartTime;
  }

  public void setTriageStartTime(LocalDateTime triageStartTime) {
    this.triageStartTime = triageStartTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlertRuleRun alertRuleRun = (AlertRuleRun) o;
    return Objects.equals(this.actualValue, alertRuleRun.actualValue) &&
        Objects.equals(this.alertRuleId, alertRuleRun.alertRuleId) &&
        Objects.equals(this.alertRuleName, alertRuleRun.alertRuleName) &&
        Objects.equals(this.alertType, alertRuleRun.alertType) &&
        Objects.equals(this.applicationName, alertRuleRun.applicationName) &&
        Objects.equals(this.created, alertRuleRun.created) &&
        Objects.equals(this.details, alertRuleRun.details) &&
        Objects.equals(this.entryIds, alertRuleRun.entryIds) &&
        Objects.equals(this.executionDuration, alertRuleRun.executionDuration) &&
        Objects.equals(this.fired, alertRuleRun.fired) &&
        Objects.equals(this.id, alertRuleRun.id) &&
        Objects.equals(this.ioc, alertRuleRun.ioc) &&
        Objects.equals(this.notified, alertRuleRun.notified) &&
        Objects.equals(this.organizationId, alertRuleRun.organizationId) &&
        Objects.equals(this.riskLevel, alertRuleRun.riskLevel) &&
        Objects.equals(this.status, alertRuleRun.status) &&
        Objects.equals(this.tags, alertRuleRun.tags) &&
        Objects.equals(this.threshold, alertRuleRun.threshold) &&
        Objects.equals(this.thresholdType, alertRuleRun.thresholdType) &&
        Objects.equals(this.triageStartTime, alertRuleRun.triageStartTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actualValue, alertRuleId, alertRuleName, alertType, applicationName, created, details, entryIds, executionDuration, fired, id, ioc, notified, organizationId, riskLevel, status, tags, threshold, thresholdType, triageStartTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlertRuleRun {\n");
    
    sb.append("    actualValue: ").append(toIndentedString(actualValue)).append("\n");
    sb.append("    alertRuleId: ").append(toIndentedString(alertRuleId)).append("\n");
    sb.append("    alertRuleName: ").append(toIndentedString(alertRuleName)).append("\n");
    sb.append("    alertType: ").append(toIndentedString(alertType)).append("\n");
    sb.append("    applicationName: ").append(toIndentedString(applicationName)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    entryIds: ").append(toIndentedString(entryIds)).append("\n");
    sb.append("    executionDuration: ").append(toIndentedString(executionDuration)).append("\n");
    sb.append("    fired: ").append(toIndentedString(fired)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ioc: ").append(toIndentedString(ioc)).append("\n");
    sb.append("    notified: ").append(toIndentedString(notified)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    riskLevel: ").append(toIndentedString(riskLevel)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    thresholdType: ").append(toIndentedString(thresholdType)).append("\n");
    sb.append("    triageStartTime: ").append(toIndentedString(triageStartTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

