/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.logsentinel.model.MachineLearningSettings;
import com.logsentinel.model.MetadataExtractionPaths;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Application
 */

public class Application {
  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("containsPersonalData")
  private Boolean containsPersonalData = null;

  @JsonProperty("created")
  private LocalDateTime created = null;

  @JsonProperty("dataMaskingPatterns")
  private List<String> dataMaskingPatterns = null;

  @JsonProperty("defaultAlertDestinations")
  private List<UUID> defaultAlertDestinations = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("detailsTransformationScript")
  private String detailsTransformationScript = null;

  @JsonProperty("disabledThreatFeeds")
  private List<UUID> disabledThreatFeeds = null;

  @JsonProperty("displayedDetailsFields")
  private String displayedDetailsFields = null;

  @JsonProperty("generateHashChain")
  private Boolean generateHashChain = null;

  @JsonProperty("generateMerkleTree")
  private Boolean generateMerkleTree = null;

  @JsonProperty("genesisEntryId")
  private UUID genesisEntryId = null;

  @JsonProperty("groupIds")
  private List<UUID> groupIds = null;

  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("ipWhiteList")
  private List<String> ipWhiteList = null;

  @JsonProperty("lastMerkleTreeGenerationTimestamp")
  private LocalDateTime lastMerkleTreeGenerationTimestamp = null;

  @JsonProperty("latestEthereumTxHash")
  private String latestEthereumTxHash = null;

  @JsonProperty("latestGlacierArchiveId")
  private String latestGlacierArchiveId = null;

  @JsonProperty("latestHashRecipientEmails")
  private List<String> latestHashRecipientEmails = null;

  @JsonProperty("logGroupingEnabled")
  private Boolean logGroupingEnabled = null;

  @JsonProperty("logLevelRegexes")
  private Map<String, String> logLevelRegexes = null;

  @JsonProperty("machineLearningSettings")
  private MachineLearningSettings machineLearningSettings = null;

  @JsonProperty("merkleTreeGenerationMinutes")
  private Integer merkleTreeGenerationMinutes = null;

  @JsonProperty("metadataExtractionPaths")
  private MetadataExtractionPaths metadataExtractionPaths = null;

  @JsonProperty("missingLogsAlertId")
  private UUID missingLogsAlertId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("openDataAnonymizationRegexes")
  private List<String> openDataAnonymizationRegexes = null;

  @JsonProperty("openDataAnonymizeBodyFields")
  private List<String> openDataAnonymizeBodyFields = null;

  @JsonProperty("openDataEnabled")
  private Boolean openDataEnabled = null;

  @JsonProperty("openDataWhitelistRegexes")
  private List<String> openDataWhitelistRegexes = null;

  @JsonProperty("organizationId")
  private UUID organizationId = null;

  @JsonProperty("partialVerificationPeriodMinutes")
  private Integer partialVerificationPeriodMinutes = null;

  @JsonProperty("performVerification")
  private Boolean performVerification = null;

  @JsonProperty("propertiesForIdenticalEntries")
  private List<String> propertiesForIdenticalEntries = null;

  @JsonProperty("retentionDays")
  private Integer retentionDays = null;

  @JsonProperty("riskLevel")
  private Integer riskLevel = null;

  @JsonProperty("signatureVerificationPublicKeys")
  private List<String> signatureVerificationPublicKeys = null;

  /**
   * Gets or Sets sourceCategory
   */
  public enum SourceCategoryEnum {
    CLOUD_INFRASTRUCTURE("CLOUD_INFRASTRUCTURE"),
    
    NETWORK_APPLIANCE("NETWORK_APPLIANCE"),
    
    DATABASE("DATABASE"),
    
    ACTIVE_DIRECTORY("ACTIVE_DIRECTORY"),
    
    ERP("ERP"),
    
    ACCOUNTING("ACCOUNTING"),
    
    HR_AND_PAYROLL("HR_AND_PAYROLL"),
    
    SERVER_OS("SERVER_OS"),
    
    FILE_SERVER("FILE_SERVER"),
    
    EMAIL_SERVER("EMAIL_SERVER"),
    
    WORKSTATION("WORKSTATION"),
    
    WEB_SERVER("WEB_SERVER"),
    
    ANTIVIRUS("ANTIVIRUS"),
    
    VPN("VPN"),
    
    DOMAIN_SPECIFIC_APPLICATION("DOMAIN_SPECIFIC_APPLICATION"),
    
    SAAS("SAAS"),
    
    IDS("IDS"),
    
    VIDEOCONFERENCING("VIDEOCONFERENCING"),
    
    CLOUD_OFFICE("CLOUD_OFFICE"),
    
    OTHER("OTHER");

    private String value;

    SourceCategoryEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SourceCategoryEnum fromValue(String text) {
      for (SourceCategoryEnum b : SourceCategoryEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("sourceCategory")
  private SourceCategoryEnum sourceCategory = null;

  @JsonProperty("storeHashesInEthereum")
  private Boolean storeHashesInEthereum = null;

  @JsonProperty("syslogId")
  private String syslogId = null;

  @JsonProperty("updated")
  private LocalDateTime updated = null;

  @JsonProperty("verificationFailureReportRecipientEmails")
  private List<String> verificationFailureReportRecipientEmails = null;

  @JsonProperty("verificationPeriodMinutes")
  private Integer verificationPeriodMinutes = null;

  /**
   * Gets or Sets warnLevel
   */
  public enum WarnLevelEnum {
    TRACE("TRACE"),
    
    DEBUG("DEBUG"),
    
    INFO("INFO"),
    
    WARN("WARN"),
    
    ERROR("ERROR"),
    
    CRITICAL("CRITICAL"),
    
    FATAL("FATAL");

    private String value;

    WarnLevelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static WarnLevelEnum fromValue(String text) {
      for (WarnLevelEnum b : WarnLevelEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("warnLevel")
  private WarnLevelEnum warnLevel = null;

  public Application active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Application containsPersonalData(Boolean containsPersonalData) {
    this.containsPersonalData = containsPersonalData;
    return this;
  }

   /**
   * Get containsPersonalData
   * @return containsPersonalData
  **/
  @ApiModelProperty(value = "")
  public Boolean isContainsPersonalData() {
    return containsPersonalData;
  }

  public void setContainsPersonalData(Boolean containsPersonalData) {
    this.containsPersonalData = containsPersonalData;
  }

  public Application created(LocalDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getCreated() {
    return created;
  }

  public void setCreated(LocalDateTime created) {
    this.created = created;
  }

  public Application dataMaskingPatterns(List<String> dataMaskingPatterns) {
    this.dataMaskingPatterns = dataMaskingPatterns;
    return this;
  }

  public Application addDataMaskingPatternsItem(String dataMaskingPatternsItem) {
    if (this.dataMaskingPatterns == null) {
      this.dataMaskingPatterns = new ArrayList<>();
    }
    this.dataMaskingPatterns.add(dataMaskingPatternsItem);
    return this;
  }

   /**
   * Get dataMaskingPatterns
   * @return dataMaskingPatterns
  **/
  @ApiModelProperty(value = "")
  public List<String> getDataMaskingPatterns() {
    return dataMaskingPatterns;
  }

  public void setDataMaskingPatterns(List<String> dataMaskingPatterns) {
    this.dataMaskingPatterns = dataMaskingPatterns;
  }

  public Application defaultAlertDestinations(List<UUID> defaultAlertDestinations) {
    this.defaultAlertDestinations = defaultAlertDestinations;
    return this;
  }

  public Application addDefaultAlertDestinationsItem(UUID defaultAlertDestinationsItem) {
    if (this.defaultAlertDestinations == null) {
      this.defaultAlertDestinations = new ArrayList<>();
    }
    this.defaultAlertDestinations.add(defaultAlertDestinationsItem);
    return this;
  }

   /**
   * Get defaultAlertDestinations
   * @return defaultAlertDestinations
  **/
  @ApiModelProperty(value = "")
  public List<UUID> getDefaultAlertDestinations() {
    return defaultAlertDestinations;
  }

  public void setDefaultAlertDestinations(List<UUID> defaultAlertDestinations) {
    this.defaultAlertDestinations = defaultAlertDestinations;
  }

  public Application description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Application detailsTransformationScript(String detailsTransformationScript) {
    this.detailsTransformationScript = detailsTransformationScript;
    return this;
  }

   /**
   * Get detailsTransformationScript
   * @return detailsTransformationScript
  **/
  @ApiModelProperty(value = "")
  public String getDetailsTransformationScript() {
    return detailsTransformationScript;
  }

  public void setDetailsTransformationScript(String detailsTransformationScript) {
    this.detailsTransformationScript = detailsTransformationScript;
  }

  public Application disabledThreatFeeds(List<UUID> disabledThreatFeeds) {
    this.disabledThreatFeeds = disabledThreatFeeds;
    return this;
  }

  public Application addDisabledThreatFeedsItem(UUID disabledThreatFeedsItem) {
    if (this.disabledThreatFeeds == null) {
      this.disabledThreatFeeds = new ArrayList<>();
    }
    this.disabledThreatFeeds.add(disabledThreatFeedsItem);
    return this;
  }

   /**
   * Get disabledThreatFeeds
   * @return disabledThreatFeeds
  **/
  @ApiModelProperty(value = "")
  public List<UUID> getDisabledThreatFeeds() {
    return disabledThreatFeeds;
  }

  public void setDisabledThreatFeeds(List<UUID> disabledThreatFeeds) {
    this.disabledThreatFeeds = disabledThreatFeeds;
  }

  public Application displayedDetailsFields(String displayedDetailsFields) {
    this.displayedDetailsFields = displayedDetailsFields;
    return this;
  }

   /**
   * Get displayedDetailsFields
   * @return displayedDetailsFields
  **/
  @ApiModelProperty(value = "")
  public String getDisplayedDetailsFields() {
    return displayedDetailsFields;
  }

  public void setDisplayedDetailsFields(String displayedDetailsFields) {
    this.displayedDetailsFields = displayedDetailsFields;
  }

  public Application generateHashChain(Boolean generateHashChain) {
    this.generateHashChain = generateHashChain;
    return this;
  }

   /**
   * Get generateHashChain
   * @return generateHashChain
  **/
  @ApiModelProperty(value = "")
  public Boolean isGenerateHashChain() {
    return generateHashChain;
  }

  public void setGenerateHashChain(Boolean generateHashChain) {
    this.generateHashChain = generateHashChain;
  }

  public Application generateMerkleTree(Boolean generateMerkleTree) {
    this.generateMerkleTree = generateMerkleTree;
    return this;
  }

   /**
   * Get generateMerkleTree
   * @return generateMerkleTree
  **/
  @ApiModelProperty(value = "")
  public Boolean isGenerateMerkleTree() {
    return generateMerkleTree;
  }

  public void setGenerateMerkleTree(Boolean generateMerkleTree) {
    this.generateMerkleTree = generateMerkleTree;
  }

  public Application genesisEntryId(UUID genesisEntryId) {
    this.genesisEntryId = genesisEntryId;
    return this;
  }

   /**
   * Get genesisEntryId
   * @return genesisEntryId
  **/
  @ApiModelProperty(value = "")
  public UUID getGenesisEntryId() {
    return genesisEntryId;
  }

  public void setGenesisEntryId(UUID genesisEntryId) {
    this.genesisEntryId = genesisEntryId;
  }

  public Application groupIds(List<UUID> groupIds) {
    this.groupIds = groupIds;
    return this;
  }

  public Application addGroupIdsItem(UUID groupIdsItem) {
    if (this.groupIds == null) {
      this.groupIds = new ArrayList<>();
    }
    this.groupIds.add(groupIdsItem);
    return this;
  }

   /**
   * Get groupIds
   * @return groupIds
  **/
  @ApiModelProperty(value = "")
  public List<UUID> getGroupIds() {
    return groupIds;
  }

  public void setGroupIds(List<UUID> groupIds) {
    this.groupIds = groupIds;
  }

  public Application id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public Application ipWhiteList(List<String> ipWhiteList) {
    this.ipWhiteList = ipWhiteList;
    return this;
  }

  public Application addIpWhiteListItem(String ipWhiteListItem) {
    if (this.ipWhiteList == null) {
      this.ipWhiteList = new ArrayList<>();
    }
    this.ipWhiteList.add(ipWhiteListItem);
    return this;
  }

   /**
   * Get ipWhiteList
   * @return ipWhiteList
  **/
  @ApiModelProperty(value = "")
  public List<String> getIpWhiteList() {
    return ipWhiteList;
  }

  public void setIpWhiteList(List<String> ipWhiteList) {
    this.ipWhiteList = ipWhiteList;
  }

  public Application lastMerkleTreeGenerationTimestamp(LocalDateTime lastMerkleTreeGenerationTimestamp) {
    this.lastMerkleTreeGenerationTimestamp = lastMerkleTreeGenerationTimestamp;
    return this;
  }

   /**
   * Get lastMerkleTreeGenerationTimestamp
   * @return lastMerkleTreeGenerationTimestamp
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getLastMerkleTreeGenerationTimestamp() {
    return lastMerkleTreeGenerationTimestamp;
  }

  public void setLastMerkleTreeGenerationTimestamp(LocalDateTime lastMerkleTreeGenerationTimestamp) {
    this.lastMerkleTreeGenerationTimestamp = lastMerkleTreeGenerationTimestamp;
  }

  public Application latestEthereumTxHash(String latestEthereumTxHash) {
    this.latestEthereumTxHash = latestEthereumTxHash;
    return this;
  }

   /**
   * Get latestEthereumTxHash
   * @return latestEthereumTxHash
  **/
  @ApiModelProperty(value = "")
  public String getLatestEthereumTxHash() {
    return latestEthereumTxHash;
  }

  public void setLatestEthereumTxHash(String latestEthereumTxHash) {
    this.latestEthereumTxHash = latestEthereumTxHash;
  }

  public Application latestGlacierArchiveId(String latestGlacierArchiveId) {
    this.latestGlacierArchiveId = latestGlacierArchiveId;
    return this;
  }

   /**
   * Get latestGlacierArchiveId
   * @return latestGlacierArchiveId
  **/
  @ApiModelProperty(value = "")
  public String getLatestGlacierArchiveId() {
    return latestGlacierArchiveId;
  }

  public void setLatestGlacierArchiveId(String latestGlacierArchiveId) {
    this.latestGlacierArchiveId = latestGlacierArchiveId;
  }

  public Application latestHashRecipientEmails(List<String> latestHashRecipientEmails) {
    this.latestHashRecipientEmails = latestHashRecipientEmails;
    return this;
  }

  public Application addLatestHashRecipientEmailsItem(String latestHashRecipientEmailsItem) {
    if (this.latestHashRecipientEmails == null) {
      this.latestHashRecipientEmails = new ArrayList<>();
    }
    this.latestHashRecipientEmails.add(latestHashRecipientEmailsItem);
    return this;
  }

   /**
   * Get latestHashRecipientEmails
   * @return latestHashRecipientEmails
  **/
  @ApiModelProperty(value = "")
  public List<String> getLatestHashRecipientEmails() {
    return latestHashRecipientEmails;
  }

  public void setLatestHashRecipientEmails(List<String> latestHashRecipientEmails) {
    this.latestHashRecipientEmails = latestHashRecipientEmails;
  }

  public Application logGroupingEnabled(Boolean logGroupingEnabled) {
    this.logGroupingEnabled = logGroupingEnabled;
    return this;
  }

   /**
   * Get logGroupingEnabled
   * @return logGroupingEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isLogGroupingEnabled() {
    return logGroupingEnabled;
  }

  public void setLogGroupingEnabled(Boolean logGroupingEnabled) {
    this.logGroupingEnabled = logGroupingEnabled;
  }

  public Application logLevelRegexes(Map<String, String> logLevelRegexes) {
    this.logLevelRegexes = logLevelRegexes;
    return this;
  }

  public Application putLogLevelRegexesItem(String key, String logLevelRegexesItem) {
    if (this.logLevelRegexes == null) {
      this.logLevelRegexes = new HashMap<>();
    }
    this.logLevelRegexes.put(key, logLevelRegexesItem);
    return this;
  }

   /**
   * Get logLevelRegexes
   * @return logLevelRegexes
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getLogLevelRegexes() {
    return logLevelRegexes;
  }

  public void setLogLevelRegexes(Map<String, String> logLevelRegexes) {
    this.logLevelRegexes = logLevelRegexes;
  }

  public Application machineLearningSettings(MachineLearningSettings machineLearningSettings) {
    this.machineLearningSettings = machineLearningSettings;
    return this;
  }

   /**
   * Get machineLearningSettings
   * @return machineLearningSettings
  **/
  @ApiModelProperty(value = "")
  public MachineLearningSettings getMachineLearningSettings() {
    return machineLearningSettings;
  }

  public void setMachineLearningSettings(MachineLearningSettings machineLearningSettings) {
    this.machineLearningSettings = machineLearningSettings;
  }

  public Application merkleTreeGenerationMinutes(Integer merkleTreeGenerationMinutes) {
    this.merkleTreeGenerationMinutes = merkleTreeGenerationMinutes;
    return this;
  }

   /**
   * Get merkleTreeGenerationMinutes
   * @return merkleTreeGenerationMinutes
  **/
  @ApiModelProperty(value = "")
  public Integer getMerkleTreeGenerationMinutes() {
    return merkleTreeGenerationMinutes;
  }

  public void setMerkleTreeGenerationMinutes(Integer merkleTreeGenerationMinutes) {
    this.merkleTreeGenerationMinutes = merkleTreeGenerationMinutes;
  }

  public Application metadataExtractionPaths(MetadataExtractionPaths metadataExtractionPaths) {
    this.metadataExtractionPaths = metadataExtractionPaths;
    return this;
  }

   /**
   * Get metadataExtractionPaths
   * @return metadataExtractionPaths
  **/
  @ApiModelProperty(value = "")
  public MetadataExtractionPaths getMetadataExtractionPaths() {
    return metadataExtractionPaths;
  }

  public void setMetadataExtractionPaths(MetadataExtractionPaths metadataExtractionPaths) {
    this.metadataExtractionPaths = metadataExtractionPaths;
  }

  public Application missingLogsAlertId(UUID missingLogsAlertId) {
    this.missingLogsAlertId = missingLogsAlertId;
    return this;
  }

   /**
   * Get missingLogsAlertId
   * @return missingLogsAlertId
  **/
  @ApiModelProperty(value = "")
  public UUID getMissingLogsAlertId() {
    return missingLogsAlertId;
  }

  public void setMissingLogsAlertId(UUID missingLogsAlertId) {
    this.missingLogsAlertId = missingLogsAlertId;
  }

  public Application name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Application openDataAnonymizationRegexes(List<String> openDataAnonymizationRegexes) {
    this.openDataAnonymizationRegexes = openDataAnonymizationRegexes;
    return this;
  }

  public Application addOpenDataAnonymizationRegexesItem(String openDataAnonymizationRegexesItem) {
    if (this.openDataAnonymizationRegexes == null) {
      this.openDataAnonymizationRegexes = new ArrayList<>();
    }
    this.openDataAnonymizationRegexes.add(openDataAnonymizationRegexesItem);
    return this;
  }

   /**
   * Get openDataAnonymizationRegexes
   * @return openDataAnonymizationRegexes
  **/
  @ApiModelProperty(value = "")
  public List<String> getOpenDataAnonymizationRegexes() {
    return openDataAnonymizationRegexes;
  }

  public void setOpenDataAnonymizationRegexes(List<String> openDataAnonymizationRegexes) {
    this.openDataAnonymizationRegexes = openDataAnonymizationRegexes;
  }

  public Application openDataAnonymizeBodyFields(List<String> openDataAnonymizeBodyFields) {
    this.openDataAnonymizeBodyFields = openDataAnonymizeBodyFields;
    return this;
  }

  public Application addOpenDataAnonymizeBodyFieldsItem(String openDataAnonymizeBodyFieldsItem) {
    if (this.openDataAnonymizeBodyFields == null) {
      this.openDataAnonymizeBodyFields = new ArrayList<>();
    }
    this.openDataAnonymizeBodyFields.add(openDataAnonymizeBodyFieldsItem);
    return this;
  }

   /**
   * Get openDataAnonymizeBodyFields
   * @return openDataAnonymizeBodyFields
  **/
  @ApiModelProperty(value = "")
  public List<String> getOpenDataAnonymizeBodyFields() {
    return openDataAnonymizeBodyFields;
  }

  public void setOpenDataAnonymizeBodyFields(List<String> openDataAnonymizeBodyFields) {
    this.openDataAnonymizeBodyFields = openDataAnonymizeBodyFields;
  }

  public Application openDataEnabled(Boolean openDataEnabled) {
    this.openDataEnabled = openDataEnabled;
    return this;
  }

   /**
   * Get openDataEnabled
   * @return openDataEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isOpenDataEnabled() {
    return openDataEnabled;
  }

  public void setOpenDataEnabled(Boolean openDataEnabled) {
    this.openDataEnabled = openDataEnabled;
  }

  public Application openDataWhitelistRegexes(List<String> openDataWhitelistRegexes) {
    this.openDataWhitelistRegexes = openDataWhitelistRegexes;
    return this;
  }

  public Application addOpenDataWhitelistRegexesItem(String openDataWhitelistRegexesItem) {
    if (this.openDataWhitelistRegexes == null) {
      this.openDataWhitelistRegexes = new ArrayList<>();
    }
    this.openDataWhitelistRegexes.add(openDataWhitelistRegexesItem);
    return this;
  }

   /**
   * Get openDataWhitelistRegexes
   * @return openDataWhitelistRegexes
  **/
  @ApiModelProperty(value = "")
  public List<String> getOpenDataWhitelistRegexes() {
    return openDataWhitelistRegexes;
  }

  public void setOpenDataWhitelistRegexes(List<String> openDataWhitelistRegexes) {
    this.openDataWhitelistRegexes = openDataWhitelistRegexes;
  }

  public Application organizationId(UUID organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @ApiModelProperty(value = "")
  public UUID getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(UUID organizationId) {
    this.organizationId = organizationId;
  }

  public Application partialVerificationPeriodMinutes(Integer partialVerificationPeriodMinutes) {
    this.partialVerificationPeriodMinutes = partialVerificationPeriodMinutes;
    return this;
  }

   /**
   * Get partialVerificationPeriodMinutes
   * @return partialVerificationPeriodMinutes
  **/
  @ApiModelProperty(value = "")
  public Integer getPartialVerificationPeriodMinutes() {
    return partialVerificationPeriodMinutes;
  }

  public void setPartialVerificationPeriodMinutes(Integer partialVerificationPeriodMinutes) {
    this.partialVerificationPeriodMinutes = partialVerificationPeriodMinutes;
  }

  public Application performVerification(Boolean performVerification) {
    this.performVerification = performVerification;
    return this;
  }

   /**
   * Get performVerification
   * @return performVerification
  **/
  @ApiModelProperty(value = "")
  public Boolean isPerformVerification() {
    return performVerification;
  }

  public void setPerformVerification(Boolean performVerification) {
    this.performVerification = performVerification;
  }

  public Application propertiesForIdenticalEntries(List<String> propertiesForIdenticalEntries) {
    this.propertiesForIdenticalEntries = propertiesForIdenticalEntries;
    return this;
  }

  public Application addPropertiesForIdenticalEntriesItem(String propertiesForIdenticalEntriesItem) {
    if (this.propertiesForIdenticalEntries == null) {
      this.propertiesForIdenticalEntries = new ArrayList<>();
    }
    this.propertiesForIdenticalEntries.add(propertiesForIdenticalEntriesItem);
    return this;
  }

   /**
   * Get propertiesForIdenticalEntries
   * @return propertiesForIdenticalEntries
  **/
  @ApiModelProperty(value = "")
  public List<String> getPropertiesForIdenticalEntries() {
    return propertiesForIdenticalEntries;
  }

  public void setPropertiesForIdenticalEntries(List<String> propertiesForIdenticalEntries) {
    this.propertiesForIdenticalEntries = propertiesForIdenticalEntries;
  }

  public Application retentionDays(Integer retentionDays) {
    this.retentionDays = retentionDays;
    return this;
  }

   /**
   * Get retentionDays
   * @return retentionDays
  **/
  @ApiModelProperty(value = "")
  public Integer getRetentionDays() {
    return retentionDays;
  }

  public void setRetentionDays(Integer retentionDays) {
    this.retentionDays = retentionDays;
  }

  public Application riskLevel(Integer riskLevel) {
    this.riskLevel = riskLevel;
    return this;
  }

   /**
   * Get riskLevel
   * @return riskLevel
  **/
  @ApiModelProperty(value = "")
  public Integer getRiskLevel() {
    return riskLevel;
  }

  public void setRiskLevel(Integer riskLevel) {
    this.riskLevel = riskLevel;
  }

  public Application signatureVerificationPublicKeys(List<String> signatureVerificationPublicKeys) {
    this.signatureVerificationPublicKeys = signatureVerificationPublicKeys;
    return this;
  }

  public Application addSignatureVerificationPublicKeysItem(String signatureVerificationPublicKeysItem) {
    if (this.signatureVerificationPublicKeys == null) {
      this.signatureVerificationPublicKeys = new ArrayList<>();
    }
    this.signatureVerificationPublicKeys.add(signatureVerificationPublicKeysItem);
    return this;
  }

   /**
   * Get signatureVerificationPublicKeys
   * @return signatureVerificationPublicKeys
  **/
  @ApiModelProperty(value = "")
  public List<String> getSignatureVerificationPublicKeys() {
    return signatureVerificationPublicKeys;
  }

  public void setSignatureVerificationPublicKeys(List<String> signatureVerificationPublicKeys) {
    this.signatureVerificationPublicKeys = signatureVerificationPublicKeys;
  }

  public Application sourceCategory(SourceCategoryEnum sourceCategory) {
    this.sourceCategory = sourceCategory;
    return this;
  }

   /**
   * Get sourceCategory
   * @return sourceCategory
  **/
  @ApiModelProperty(value = "")
  public SourceCategoryEnum getSourceCategory() {
    return sourceCategory;
  }

  public void setSourceCategory(SourceCategoryEnum sourceCategory) {
    this.sourceCategory = sourceCategory;
  }

  public Application storeHashesInEthereum(Boolean storeHashesInEthereum) {
    this.storeHashesInEthereum = storeHashesInEthereum;
    return this;
  }

   /**
   * Get storeHashesInEthereum
   * @return storeHashesInEthereum
  **/
  @ApiModelProperty(value = "")
  public Boolean isStoreHashesInEthereum() {
    return storeHashesInEthereum;
  }

  public void setStoreHashesInEthereum(Boolean storeHashesInEthereum) {
    this.storeHashesInEthereum = storeHashesInEthereum;
  }

  public Application syslogId(String syslogId) {
    this.syslogId = syslogId;
    return this;
  }

   /**
   * Get syslogId
   * @return syslogId
  **/
  @ApiModelProperty(value = "")
  public String getSyslogId() {
    return syslogId;
  }

  public void setSyslogId(String syslogId) {
    this.syslogId = syslogId;
  }

  public Application updated(LocalDateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getUpdated() {
    return updated;
  }

  public void setUpdated(LocalDateTime updated) {
    this.updated = updated;
  }

  public Application verificationFailureReportRecipientEmails(List<String> verificationFailureReportRecipientEmails) {
    this.verificationFailureReportRecipientEmails = verificationFailureReportRecipientEmails;
    return this;
  }

  public Application addVerificationFailureReportRecipientEmailsItem(String verificationFailureReportRecipientEmailsItem) {
    if (this.verificationFailureReportRecipientEmails == null) {
      this.verificationFailureReportRecipientEmails = new ArrayList<>();
    }
    this.verificationFailureReportRecipientEmails.add(verificationFailureReportRecipientEmailsItem);
    return this;
  }

   /**
   * Get verificationFailureReportRecipientEmails
   * @return verificationFailureReportRecipientEmails
  **/
  @ApiModelProperty(value = "")
  public List<String> getVerificationFailureReportRecipientEmails() {
    return verificationFailureReportRecipientEmails;
  }

  public void setVerificationFailureReportRecipientEmails(List<String> verificationFailureReportRecipientEmails) {
    this.verificationFailureReportRecipientEmails = verificationFailureReportRecipientEmails;
  }

  public Application verificationPeriodMinutes(Integer verificationPeriodMinutes) {
    this.verificationPeriodMinutes = verificationPeriodMinutes;
    return this;
  }

   /**
   * Get verificationPeriodMinutes
   * @return verificationPeriodMinutes
  **/
  @ApiModelProperty(value = "")
  public Integer getVerificationPeriodMinutes() {
    return verificationPeriodMinutes;
  }

  public void setVerificationPeriodMinutes(Integer verificationPeriodMinutes) {
    this.verificationPeriodMinutes = verificationPeriodMinutes;
  }

  public Application warnLevel(WarnLevelEnum warnLevel) {
    this.warnLevel = warnLevel;
    return this;
  }

   /**
   * Get warnLevel
   * @return warnLevel
  **/
  @ApiModelProperty(value = "")
  public WarnLevelEnum getWarnLevel() {
    return warnLevel;
  }

  public void setWarnLevel(WarnLevelEnum warnLevel) {
    this.warnLevel = warnLevel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Application application = (Application) o;
    return Objects.equals(this.active, application.active) &&
        Objects.equals(this.containsPersonalData, application.containsPersonalData) &&
        Objects.equals(this.created, application.created) &&
        Objects.equals(this.dataMaskingPatterns, application.dataMaskingPatterns) &&
        Objects.equals(this.defaultAlertDestinations, application.defaultAlertDestinations) &&
        Objects.equals(this.description, application.description) &&
        Objects.equals(this.detailsTransformationScript, application.detailsTransformationScript) &&
        Objects.equals(this.disabledThreatFeeds, application.disabledThreatFeeds) &&
        Objects.equals(this.displayedDetailsFields, application.displayedDetailsFields) &&
        Objects.equals(this.generateHashChain, application.generateHashChain) &&
        Objects.equals(this.generateMerkleTree, application.generateMerkleTree) &&
        Objects.equals(this.genesisEntryId, application.genesisEntryId) &&
        Objects.equals(this.groupIds, application.groupIds) &&
        Objects.equals(this.id, application.id) &&
        Objects.equals(this.ipWhiteList, application.ipWhiteList) &&
        Objects.equals(this.lastMerkleTreeGenerationTimestamp, application.lastMerkleTreeGenerationTimestamp) &&
        Objects.equals(this.latestEthereumTxHash, application.latestEthereumTxHash) &&
        Objects.equals(this.latestGlacierArchiveId, application.latestGlacierArchiveId) &&
        Objects.equals(this.latestHashRecipientEmails, application.latestHashRecipientEmails) &&
        Objects.equals(this.logGroupingEnabled, application.logGroupingEnabled) &&
        Objects.equals(this.logLevelRegexes, application.logLevelRegexes) &&
        Objects.equals(this.machineLearningSettings, application.machineLearningSettings) &&
        Objects.equals(this.merkleTreeGenerationMinutes, application.merkleTreeGenerationMinutes) &&
        Objects.equals(this.metadataExtractionPaths, application.metadataExtractionPaths) &&
        Objects.equals(this.missingLogsAlertId, application.missingLogsAlertId) &&
        Objects.equals(this.name, application.name) &&
        Objects.equals(this.openDataAnonymizationRegexes, application.openDataAnonymizationRegexes) &&
        Objects.equals(this.openDataAnonymizeBodyFields, application.openDataAnonymizeBodyFields) &&
        Objects.equals(this.openDataEnabled, application.openDataEnabled) &&
        Objects.equals(this.openDataWhitelistRegexes, application.openDataWhitelistRegexes) &&
        Objects.equals(this.organizationId, application.organizationId) &&
        Objects.equals(this.partialVerificationPeriodMinutes, application.partialVerificationPeriodMinutes) &&
        Objects.equals(this.performVerification, application.performVerification) &&
        Objects.equals(this.propertiesForIdenticalEntries, application.propertiesForIdenticalEntries) &&
        Objects.equals(this.retentionDays, application.retentionDays) &&
        Objects.equals(this.riskLevel, application.riskLevel) &&
        Objects.equals(this.signatureVerificationPublicKeys, application.signatureVerificationPublicKeys) &&
        Objects.equals(this.sourceCategory, application.sourceCategory) &&
        Objects.equals(this.storeHashesInEthereum, application.storeHashesInEthereum) &&
        Objects.equals(this.syslogId, application.syslogId) &&
        Objects.equals(this.updated, application.updated) &&
        Objects.equals(this.verificationFailureReportRecipientEmails, application.verificationFailureReportRecipientEmails) &&
        Objects.equals(this.verificationPeriodMinutes, application.verificationPeriodMinutes) &&
        Objects.equals(this.warnLevel, application.warnLevel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, containsPersonalData, created, dataMaskingPatterns, defaultAlertDestinations, description, detailsTransformationScript, disabledThreatFeeds, displayedDetailsFields, generateHashChain, generateMerkleTree, genesisEntryId, groupIds, id, ipWhiteList, lastMerkleTreeGenerationTimestamp, latestEthereumTxHash, latestGlacierArchiveId, latestHashRecipientEmails, logGroupingEnabled, logLevelRegexes, machineLearningSettings, merkleTreeGenerationMinutes, metadataExtractionPaths, missingLogsAlertId, name, openDataAnonymizationRegexes, openDataAnonymizeBodyFields, openDataEnabled, openDataWhitelistRegexes, organizationId, partialVerificationPeriodMinutes, performVerification, propertiesForIdenticalEntries, retentionDays, riskLevel, signatureVerificationPublicKeys, sourceCategory, storeHashesInEthereum, syslogId, updated, verificationFailureReportRecipientEmails, verificationPeriodMinutes, warnLevel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Application {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    containsPersonalData: ").append(toIndentedString(containsPersonalData)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    dataMaskingPatterns: ").append(toIndentedString(dataMaskingPatterns)).append("\n");
    sb.append("    defaultAlertDestinations: ").append(toIndentedString(defaultAlertDestinations)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    detailsTransformationScript: ").append(toIndentedString(detailsTransformationScript)).append("\n");
    sb.append("    disabledThreatFeeds: ").append(toIndentedString(disabledThreatFeeds)).append("\n");
    sb.append("    displayedDetailsFields: ").append(toIndentedString(displayedDetailsFields)).append("\n");
    sb.append("    generateHashChain: ").append(toIndentedString(generateHashChain)).append("\n");
    sb.append("    generateMerkleTree: ").append(toIndentedString(generateMerkleTree)).append("\n");
    sb.append("    genesisEntryId: ").append(toIndentedString(genesisEntryId)).append("\n");
    sb.append("    groupIds: ").append(toIndentedString(groupIds)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ipWhiteList: ").append(toIndentedString(ipWhiteList)).append("\n");
    sb.append("    lastMerkleTreeGenerationTimestamp: ").append(toIndentedString(lastMerkleTreeGenerationTimestamp)).append("\n");
    sb.append("    latestEthereumTxHash: ").append(toIndentedString(latestEthereumTxHash)).append("\n");
    sb.append("    latestGlacierArchiveId: ").append(toIndentedString(latestGlacierArchiveId)).append("\n");
    sb.append("    latestHashRecipientEmails: ").append(toIndentedString(latestHashRecipientEmails)).append("\n");
    sb.append("    logGroupingEnabled: ").append(toIndentedString(logGroupingEnabled)).append("\n");
    sb.append("    logLevelRegexes: ").append(toIndentedString(logLevelRegexes)).append("\n");
    sb.append("    machineLearningSettings: ").append(toIndentedString(machineLearningSettings)).append("\n");
    sb.append("    merkleTreeGenerationMinutes: ").append(toIndentedString(merkleTreeGenerationMinutes)).append("\n");
    sb.append("    metadataExtractionPaths: ").append(toIndentedString(metadataExtractionPaths)).append("\n");
    sb.append("    missingLogsAlertId: ").append(toIndentedString(missingLogsAlertId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    openDataAnonymizationRegexes: ").append(toIndentedString(openDataAnonymizationRegexes)).append("\n");
    sb.append("    openDataAnonymizeBodyFields: ").append(toIndentedString(openDataAnonymizeBodyFields)).append("\n");
    sb.append("    openDataEnabled: ").append(toIndentedString(openDataEnabled)).append("\n");
    sb.append("    openDataWhitelistRegexes: ").append(toIndentedString(openDataWhitelistRegexes)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    partialVerificationPeriodMinutes: ").append(toIndentedString(partialVerificationPeriodMinutes)).append("\n");
    sb.append("    performVerification: ").append(toIndentedString(performVerification)).append("\n");
    sb.append("    propertiesForIdenticalEntries: ").append(toIndentedString(propertiesForIdenticalEntries)).append("\n");
    sb.append("    retentionDays: ").append(toIndentedString(retentionDays)).append("\n");
    sb.append("    riskLevel: ").append(toIndentedString(riskLevel)).append("\n");
    sb.append("    signatureVerificationPublicKeys: ").append(toIndentedString(signatureVerificationPublicKeys)).append("\n");
    sb.append("    sourceCategory: ").append(toIndentedString(sourceCategory)).append("\n");
    sb.append("    storeHashesInEthereum: ").append(toIndentedString(storeHashesInEthereum)).append("\n");
    sb.append("    syslogId: ").append(toIndentedString(syslogId)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    verificationFailureReportRecipientEmails: ").append(toIndentedString(verificationFailureReportRecipientEmails)).append("\n");
    sb.append("    verificationPeriodMinutes: ").append(toIndentedString(verificationPeriodMinutes)).append("\n");
    sb.append("    warnLevel: ").append(toIndentedString(warnLevel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

