/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.logsentinel.model.MetadataExtractionPaths;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * ApplicationRequest
 */

public class ApplicationRequest {
  @JsonProperty("automaticBehaviorMonitoring")
  private Boolean automaticBehaviorMonitoring = null;

  @JsonProperty("containsPersonalData")
  private Boolean containsPersonalData = null;

  @JsonProperty("dataMaskingPatterns")
  private List<String> dataMaskingPatterns = null;

  @JsonProperty("defaultAlertDestinations")
  private List<UUID> defaultAlertDestinations = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("detailsTransformationScript")
  private String detailsTransformationScript = null;

  @JsonProperty("disabledThreatFeeds")
  private List<UUID> disabledThreatFeeds = null;

  @JsonProperty("discardLogConditions")
  private List<String> discardLogConditions = null;

  @JsonProperty("displayedDetailsFields")
  private String displayedDetailsFields = null;

  @JsonProperty("extractionOverrideEnabled")
  private Boolean extractionOverrideEnabled = null;

  @JsonProperty("generateHashChain")
  private Boolean generateHashChain = null;

  @JsonProperty("generateMerkleTree")
  private Boolean generateMerkleTree = null;

  @JsonProperty("groupIds")
  private List<UUID> groupIds = null;

  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("ipWhiteList")
  private List<String> ipWhiteList = null;

  @JsonProperty("latestHashRecipientEmails")
  private List<String> latestHashRecipientEmails = null;

  @JsonProperty("logGroupingEnabled")
  private Boolean logGroupingEnabled = null;

  @JsonProperty("logLevelRegexes")
  private Map<String, String> logLevelRegexes = null;

  @JsonProperty("metadataExtractionPaths")
  private MetadataExtractionPaths metadataExtractionPaths = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("newThreatIntelAlertPeriodHours")
  private Integer newThreatIntelAlertPeriodHours = null;

  @JsonProperty("openDataAnonymizationRegexes")
  private List<String> openDataAnonymizationRegexes = null;

  @JsonProperty("openDataAnonymizeBodyFields")
  private List<String> openDataAnonymizeBodyFields = null;

  @JsonProperty("openDataEnabled")
  private Boolean openDataEnabled = null;

  @JsonProperty("openDataWhitelistRegexes")
  private List<String> openDataWhitelistRegexes = null;

  @JsonProperty("partialVerificationPeriodMinutes")
  private Integer partialVerificationPeriodMinutes = null;

  @JsonProperty("propertiesForIdenticalEntries")
  private List<String> propertiesForIdenticalEntries = null;

  @JsonProperty("retentionDays")
  private Integer retentionDays = null;

  @JsonProperty("riskLevel")
  private Integer riskLevel = null;

  @JsonProperty("signatureVerificationPublicKeys")
  private List<String> signatureVerificationPublicKeys = null;

  @JsonProperty("skipThreatIntelligenceParams")
  private Map<String, String> skipThreatIntelligenceParams = null;

  @JsonProperty("skipThreatIntelligenceRegex")
  private String skipThreatIntelligenceRegex = null;

  /**
   * Gets or Sets sourceCategory
   */
  public enum SourceCategoryEnum {
    CLOUD_INFRASTRUCTURE("CLOUD_INFRASTRUCTURE"),
    
    NETWORK_APPLIANCE("NETWORK_APPLIANCE"),
    
    DATABASE("DATABASE"),
    
    ACTIVE_DIRECTORY("ACTIVE_DIRECTORY"),
    
    ERP("ERP"),
    
    ACCOUNTING("ACCOUNTING"),
    
    HR_AND_PAYROLL("HR_AND_PAYROLL"),
    
    SERVER_OS("SERVER_OS"),
    
    FILE_SERVER("FILE_SERVER"),
    
    EMAIL_SERVER("EMAIL_SERVER"),
    
    WORKSTATION("WORKSTATION"),
    
    WEB_SERVER("WEB_SERVER"),
    
    ANTIVIRUS("ANTIVIRUS"),
    
    VPN("VPN"),
    
    DOMAIN_SPECIFIC_APPLICATION("DOMAIN_SPECIFIC_APPLICATION"),
    
    SAAS("SAAS"),
    
    IDS("IDS"),
    
    VIDEOCONFERENCING("VIDEOCONFERENCING"),
    
    CLOUD_OFFICE("CLOUD_OFFICE"),
    
    OTHER("OTHER");

    private String value;

    SourceCategoryEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SourceCategoryEnum fromValue(String text) {
      for (SourceCategoryEnum b : SourceCategoryEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("sourceCategory")
  private SourceCategoryEnum sourceCategory = null;

  @JsonProperty("storeHashesInEthereum")
  private Boolean storeHashesInEthereum = null;

  @JsonProperty("verificationFailureReportRecipientEmails")
  private List<String> verificationFailureReportRecipientEmails = null;

  @JsonProperty("verificationPeriodMinutes")
  private Integer verificationPeriodMinutes = null;

  /**
   * Gets or Sets warnLevel
   */
  public enum WarnLevelEnum {
    TRACE("TRACE"),
    
    DEBUG("DEBUG"),
    
    INFO("INFO"),
    
    WARN("WARN"),
    
    ERROR("ERROR"),
    
    CRITICAL("CRITICAL"),
    
    FATAL("FATAL");

    private String value;

    WarnLevelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static WarnLevelEnum fromValue(String text) {
      for (WarnLevelEnum b : WarnLevelEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("warnLevel")
  private WarnLevelEnum warnLevel = null;

  public ApplicationRequest automaticBehaviorMonitoring(Boolean automaticBehaviorMonitoring) {
    this.automaticBehaviorMonitoring = automaticBehaviorMonitoring;
    return this;
  }

   /**
   * Get automaticBehaviorMonitoring
   * @return automaticBehaviorMonitoring
  **/
  @ApiModelProperty(value = "")
  public Boolean isAutomaticBehaviorMonitoring() {
    return automaticBehaviorMonitoring;
  }

  public void setAutomaticBehaviorMonitoring(Boolean automaticBehaviorMonitoring) {
    this.automaticBehaviorMonitoring = automaticBehaviorMonitoring;
  }

  public ApplicationRequest containsPersonalData(Boolean containsPersonalData) {
    this.containsPersonalData = containsPersonalData;
    return this;
  }

   /**
   * Get containsPersonalData
   * @return containsPersonalData
  **/
  @ApiModelProperty(value = "")
  public Boolean isContainsPersonalData() {
    return containsPersonalData;
  }

  public void setContainsPersonalData(Boolean containsPersonalData) {
    this.containsPersonalData = containsPersonalData;
  }

  public ApplicationRequest dataMaskingPatterns(List<String> dataMaskingPatterns) {
    this.dataMaskingPatterns = dataMaskingPatterns;
    return this;
  }

  public ApplicationRequest addDataMaskingPatternsItem(String dataMaskingPatternsItem) {
    if (this.dataMaskingPatterns == null) {
      this.dataMaskingPatterns = new ArrayList<>();
    }
    this.dataMaskingPatterns.add(dataMaskingPatternsItem);
    return this;
  }

   /**
   * Get dataMaskingPatterns
   * @return dataMaskingPatterns
  **/
  @ApiModelProperty(value = "")
  public List<String> getDataMaskingPatterns() {
    return dataMaskingPatterns;
  }

  public void setDataMaskingPatterns(List<String> dataMaskingPatterns) {
    this.dataMaskingPatterns = dataMaskingPatterns;
  }

  public ApplicationRequest defaultAlertDestinations(List<UUID> defaultAlertDestinations) {
    this.defaultAlertDestinations = defaultAlertDestinations;
    return this;
  }

  public ApplicationRequest addDefaultAlertDestinationsItem(UUID defaultAlertDestinationsItem) {
    if (this.defaultAlertDestinations == null) {
      this.defaultAlertDestinations = new ArrayList<>();
    }
    this.defaultAlertDestinations.add(defaultAlertDestinationsItem);
    return this;
  }

   /**
   * Get defaultAlertDestinations
   * @return defaultAlertDestinations
  **/
  @ApiModelProperty(value = "")
  public List<UUID> getDefaultAlertDestinations() {
    return defaultAlertDestinations;
  }

  public void setDefaultAlertDestinations(List<UUID> defaultAlertDestinations) {
    this.defaultAlertDestinations = defaultAlertDestinations;
  }

  public ApplicationRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ApplicationRequest detailsTransformationScript(String detailsTransformationScript) {
    this.detailsTransformationScript = detailsTransformationScript;
    return this;
  }

   /**
   * Get detailsTransformationScript
   * @return detailsTransformationScript
  **/
  @ApiModelProperty(value = "")
  public String getDetailsTransformationScript() {
    return detailsTransformationScript;
  }

  public void setDetailsTransformationScript(String detailsTransformationScript) {
    this.detailsTransformationScript = detailsTransformationScript;
  }

  public ApplicationRequest disabledThreatFeeds(List<UUID> disabledThreatFeeds) {
    this.disabledThreatFeeds = disabledThreatFeeds;
    return this;
  }

  public ApplicationRequest addDisabledThreatFeedsItem(UUID disabledThreatFeedsItem) {
    if (this.disabledThreatFeeds == null) {
      this.disabledThreatFeeds = new ArrayList<>();
    }
    this.disabledThreatFeeds.add(disabledThreatFeedsItem);
    return this;
  }

   /**
   * Get disabledThreatFeeds
   * @return disabledThreatFeeds
  **/
  @ApiModelProperty(value = "")
  public List<UUID> getDisabledThreatFeeds() {
    return disabledThreatFeeds;
  }

  public void setDisabledThreatFeeds(List<UUID> disabledThreatFeeds) {
    this.disabledThreatFeeds = disabledThreatFeeds;
  }

  public ApplicationRequest discardLogConditions(List<String> discardLogConditions) {
    this.discardLogConditions = discardLogConditions;
    return this;
  }

  public ApplicationRequest addDiscardLogConditionsItem(String discardLogConditionsItem) {
    if (this.discardLogConditions == null) {
      this.discardLogConditions = new ArrayList<>();
    }
    this.discardLogConditions.add(discardLogConditionsItem);
    return this;
  }

   /**
   * Get discardLogConditions
   * @return discardLogConditions
  **/
  @ApiModelProperty(value = "")
  public List<String> getDiscardLogConditions() {
    return discardLogConditions;
  }

  public void setDiscardLogConditions(List<String> discardLogConditions) {
    this.discardLogConditions = discardLogConditions;
  }

  public ApplicationRequest displayedDetailsFields(String displayedDetailsFields) {
    this.displayedDetailsFields = displayedDetailsFields;
    return this;
  }

   /**
   * Get displayedDetailsFields
   * @return displayedDetailsFields
  **/
  @ApiModelProperty(value = "")
  public String getDisplayedDetailsFields() {
    return displayedDetailsFields;
  }

  public void setDisplayedDetailsFields(String displayedDetailsFields) {
    this.displayedDetailsFields = displayedDetailsFields;
  }

  public ApplicationRequest extractionOverrideEnabled(Boolean extractionOverrideEnabled) {
    this.extractionOverrideEnabled = extractionOverrideEnabled;
    return this;
  }

   /**
   * Get extractionOverrideEnabled
   * @return extractionOverrideEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isExtractionOverrideEnabled() {
    return extractionOverrideEnabled;
  }

  public void setExtractionOverrideEnabled(Boolean extractionOverrideEnabled) {
    this.extractionOverrideEnabled = extractionOverrideEnabled;
  }

  public ApplicationRequest generateHashChain(Boolean generateHashChain) {
    this.generateHashChain = generateHashChain;
    return this;
  }

   /**
   * Get generateHashChain
   * @return generateHashChain
  **/
  @ApiModelProperty(value = "")
  public Boolean isGenerateHashChain() {
    return generateHashChain;
  }

  public void setGenerateHashChain(Boolean generateHashChain) {
    this.generateHashChain = generateHashChain;
  }

  public ApplicationRequest generateMerkleTree(Boolean generateMerkleTree) {
    this.generateMerkleTree = generateMerkleTree;
    return this;
  }

   /**
   * Get generateMerkleTree
   * @return generateMerkleTree
  **/
  @ApiModelProperty(value = "")
  public Boolean isGenerateMerkleTree() {
    return generateMerkleTree;
  }

  public void setGenerateMerkleTree(Boolean generateMerkleTree) {
    this.generateMerkleTree = generateMerkleTree;
  }

  public ApplicationRequest groupIds(List<UUID> groupIds) {
    this.groupIds = groupIds;
    return this;
  }

  public ApplicationRequest addGroupIdsItem(UUID groupIdsItem) {
    if (this.groupIds == null) {
      this.groupIds = new ArrayList<>();
    }
    this.groupIds.add(groupIdsItem);
    return this;
  }

   /**
   * Get groupIds
   * @return groupIds
  **/
  @ApiModelProperty(value = "")
  public List<UUID> getGroupIds() {
    return groupIds;
  }

  public void setGroupIds(List<UUID> groupIds) {
    this.groupIds = groupIds;
  }

  public ApplicationRequest id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public ApplicationRequest ipWhiteList(List<String> ipWhiteList) {
    this.ipWhiteList = ipWhiteList;
    return this;
  }

  public ApplicationRequest addIpWhiteListItem(String ipWhiteListItem) {
    if (this.ipWhiteList == null) {
      this.ipWhiteList = new ArrayList<>();
    }
    this.ipWhiteList.add(ipWhiteListItem);
    return this;
  }

   /**
   * Get ipWhiteList
   * @return ipWhiteList
  **/
  @ApiModelProperty(value = "")
  public List<String> getIpWhiteList() {
    return ipWhiteList;
  }

  public void setIpWhiteList(List<String> ipWhiteList) {
    this.ipWhiteList = ipWhiteList;
  }

  public ApplicationRequest latestHashRecipientEmails(List<String> latestHashRecipientEmails) {
    this.latestHashRecipientEmails = latestHashRecipientEmails;
    return this;
  }

  public ApplicationRequest addLatestHashRecipientEmailsItem(String latestHashRecipientEmailsItem) {
    if (this.latestHashRecipientEmails == null) {
      this.latestHashRecipientEmails = new ArrayList<>();
    }
    this.latestHashRecipientEmails.add(latestHashRecipientEmailsItem);
    return this;
  }

   /**
   * Get latestHashRecipientEmails
   * @return latestHashRecipientEmails
  **/
  @ApiModelProperty(value = "")
  public List<String> getLatestHashRecipientEmails() {
    return latestHashRecipientEmails;
  }

  public void setLatestHashRecipientEmails(List<String> latestHashRecipientEmails) {
    this.latestHashRecipientEmails = latestHashRecipientEmails;
  }

  public ApplicationRequest logGroupingEnabled(Boolean logGroupingEnabled) {
    this.logGroupingEnabled = logGroupingEnabled;
    return this;
  }

   /**
   * Get logGroupingEnabled
   * @return logGroupingEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isLogGroupingEnabled() {
    return logGroupingEnabled;
  }

  public void setLogGroupingEnabled(Boolean logGroupingEnabled) {
    this.logGroupingEnabled = logGroupingEnabled;
  }

  public ApplicationRequest logLevelRegexes(Map<String, String> logLevelRegexes) {
    this.logLevelRegexes = logLevelRegexes;
    return this;
  }

  public ApplicationRequest putLogLevelRegexesItem(String key, String logLevelRegexesItem) {
    if (this.logLevelRegexes == null) {
      this.logLevelRegexes = new HashMap<>();
    }
    this.logLevelRegexes.put(key, logLevelRegexesItem);
    return this;
  }

   /**
   * Get logLevelRegexes
   * @return logLevelRegexes
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getLogLevelRegexes() {
    return logLevelRegexes;
  }

  public void setLogLevelRegexes(Map<String, String> logLevelRegexes) {
    this.logLevelRegexes = logLevelRegexes;
  }

  public ApplicationRequest metadataExtractionPaths(MetadataExtractionPaths metadataExtractionPaths) {
    this.metadataExtractionPaths = metadataExtractionPaths;
    return this;
  }

   /**
   * Get metadataExtractionPaths
   * @return metadataExtractionPaths
  **/
  @ApiModelProperty(value = "")
  public MetadataExtractionPaths getMetadataExtractionPaths() {
    return metadataExtractionPaths;
  }

  public void setMetadataExtractionPaths(MetadataExtractionPaths metadataExtractionPaths) {
    this.metadataExtractionPaths = metadataExtractionPaths;
  }

  public ApplicationRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ApplicationRequest newThreatIntelAlertPeriodHours(Integer newThreatIntelAlertPeriodHours) {
    this.newThreatIntelAlertPeriodHours = newThreatIntelAlertPeriodHours;
    return this;
  }

   /**
   * Get newThreatIntelAlertPeriodHours
   * @return newThreatIntelAlertPeriodHours
  **/
  @ApiModelProperty(value = "")
  public Integer getNewThreatIntelAlertPeriodHours() {
    return newThreatIntelAlertPeriodHours;
  }

  public void setNewThreatIntelAlertPeriodHours(Integer newThreatIntelAlertPeriodHours) {
    this.newThreatIntelAlertPeriodHours = newThreatIntelAlertPeriodHours;
  }

  public ApplicationRequest openDataAnonymizationRegexes(List<String> openDataAnonymizationRegexes) {
    this.openDataAnonymizationRegexes = openDataAnonymizationRegexes;
    return this;
  }

  public ApplicationRequest addOpenDataAnonymizationRegexesItem(String openDataAnonymizationRegexesItem) {
    if (this.openDataAnonymizationRegexes == null) {
      this.openDataAnonymizationRegexes = new ArrayList<>();
    }
    this.openDataAnonymizationRegexes.add(openDataAnonymizationRegexesItem);
    return this;
  }

   /**
   * Get openDataAnonymizationRegexes
   * @return openDataAnonymizationRegexes
  **/
  @ApiModelProperty(value = "")
  public List<String> getOpenDataAnonymizationRegexes() {
    return openDataAnonymizationRegexes;
  }

  public void setOpenDataAnonymizationRegexes(List<String> openDataAnonymizationRegexes) {
    this.openDataAnonymizationRegexes = openDataAnonymizationRegexes;
  }

  public ApplicationRequest openDataAnonymizeBodyFields(List<String> openDataAnonymizeBodyFields) {
    this.openDataAnonymizeBodyFields = openDataAnonymizeBodyFields;
    return this;
  }

  public ApplicationRequest addOpenDataAnonymizeBodyFieldsItem(String openDataAnonymizeBodyFieldsItem) {
    if (this.openDataAnonymizeBodyFields == null) {
      this.openDataAnonymizeBodyFields = new ArrayList<>();
    }
    this.openDataAnonymizeBodyFields.add(openDataAnonymizeBodyFieldsItem);
    return this;
  }

   /**
   * Get openDataAnonymizeBodyFields
   * @return openDataAnonymizeBodyFields
  **/
  @ApiModelProperty(value = "")
  public List<String> getOpenDataAnonymizeBodyFields() {
    return openDataAnonymizeBodyFields;
  }

  public void setOpenDataAnonymizeBodyFields(List<String> openDataAnonymizeBodyFields) {
    this.openDataAnonymizeBodyFields = openDataAnonymizeBodyFields;
  }

  public ApplicationRequest openDataEnabled(Boolean openDataEnabled) {
    this.openDataEnabled = openDataEnabled;
    return this;
  }

   /**
   * Get openDataEnabled
   * @return openDataEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isOpenDataEnabled() {
    return openDataEnabled;
  }

  public void setOpenDataEnabled(Boolean openDataEnabled) {
    this.openDataEnabled = openDataEnabled;
  }

  public ApplicationRequest openDataWhitelistRegexes(List<String> openDataWhitelistRegexes) {
    this.openDataWhitelistRegexes = openDataWhitelistRegexes;
    return this;
  }

  public ApplicationRequest addOpenDataWhitelistRegexesItem(String openDataWhitelistRegexesItem) {
    if (this.openDataWhitelistRegexes == null) {
      this.openDataWhitelistRegexes = new ArrayList<>();
    }
    this.openDataWhitelistRegexes.add(openDataWhitelistRegexesItem);
    return this;
  }

   /**
   * Get openDataWhitelistRegexes
   * @return openDataWhitelistRegexes
  **/
  @ApiModelProperty(value = "")
  public List<String> getOpenDataWhitelistRegexes() {
    return openDataWhitelistRegexes;
  }

  public void setOpenDataWhitelistRegexes(List<String> openDataWhitelistRegexes) {
    this.openDataWhitelistRegexes = openDataWhitelistRegexes;
  }

  public ApplicationRequest partialVerificationPeriodMinutes(Integer partialVerificationPeriodMinutes) {
    this.partialVerificationPeriodMinutes = partialVerificationPeriodMinutes;
    return this;
  }

   /**
   * Get partialVerificationPeriodMinutes
   * @return partialVerificationPeriodMinutes
  **/
  @ApiModelProperty(value = "")
  public Integer getPartialVerificationPeriodMinutes() {
    return partialVerificationPeriodMinutes;
  }

  public void setPartialVerificationPeriodMinutes(Integer partialVerificationPeriodMinutes) {
    this.partialVerificationPeriodMinutes = partialVerificationPeriodMinutes;
  }

  public ApplicationRequest propertiesForIdenticalEntries(List<String> propertiesForIdenticalEntries) {
    this.propertiesForIdenticalEntries = propertiesForIdenticalEntries;
    return this;
  }

  public ApplicationRequest addPropertiesForIdenticalEntriesItem(String propertiesForIdenticalEntriesItem) {
    if (this.propertiesForIdenticalEntries == null) {
      this.propertiesForIdenticalEntries = new ArrayList<>();
    }
    this.propertiesForIdenticalEntries.add(propertiesForIdenticalEntriesItem);
    return this;
  }

   /**
   * Get propertiesForIdenticalEntries
   * @return propertiesForIdenticalEntries
  **/
  @ApiModelProperty(value = "")
  public List<String> getPropertiesForIdenticalEntries() {
    return propertiesForIdenticalEntries;
  }

  public void setPropertiesForIdenticalEntries(List<String> propertiesForIdenticalEntries) {
    this.propertiesForIdenticalEntries = propertiesForIdenticalEntries;
  }

  public ApplicationRequest retentionDays(Integer retentionDays) {
    this.retentionDays = retentionDays;
    return this;
  }

   /**
   * Get retentionDays
   * @return retentionDays
  **/
  @ApiModelProperty(value = "")
  public Integer getRetentionDays() {
    return retentionDays;
  }

  public void setRetentionDays(Integer retentionDays) {
    this.retentionDays = retentionDays;
  }

  public ApplicationRequest riskLevel(Integer riskLevel) {
    this.riskLevel = riskLevel;
    return this;
  }

   /**
   * Get riskLevel
   * @return riskLevel
  **/
  @ApiModelProperty(value = "")
  public Integer getRiskLevel() {
    return riskLevel;
  }

  public void setRiskLevel(Integer riskLevel) {
    this.riskLevel = riskLevel;
  }

  public ApplicationRequest signatureVerificationPublicKeys(List<String> signatureVerificationPublicKeys) {
    this.signatureVerificationPublicKeys = signatureVerificationPublicKeys;
    return this;
  }

  public ApplicationRequest addSignatureVerificationPublicKeysItem(String signatureVerificationPublicKeysItem) {
    if (this.signatureVerificationPublicKeys == null) {
      this.signatureVerificationPublicKeys = new ArrayList<>();
    }
    this.signatureVerificationPublicKeys.add(signatureVerificationPublicKeysItem);
    return this;
  }

   /**
   * Get signatureVerificationPublicKeys
   * @return signatureVerificationPublicKeys
  **/
  @ApiModelProperty(value = "")
  public List<String> getSignatureVerificationPublicKeys() {
    return signatureVerificationPublicKeys;
  }

  public void setSignatureVerificationPublicKeys(List<String> signatureVerificationPublicKeys) {
    this.signatureVerificationPublicKeys = signatureVerificationPublicKeys;
  }

  public ApplicationRequest skipThreatIntelligenceParams(Map<String, String> skipThreatIntelligenceParams) {
    this.skipThreatIntelligenceParams = skipThreatIntelligenceParams;
    return this;
  }

  public ApplicationRequest putSkipThreatIntelligenceParamsItem(String key, String skipThreatIntelligenceParamsItem) {
    if (this.skipThreatIntelligenceParams == null) {
      this.skipThreatIntelligenceParams = new HashMap<>();
    }
    this.skipThreatIntelligenceParams.put(key, skipThreatIntelligenceParamsItem);
    return this;
  }

   /**
   * Get skipThreatIntelligenceParams
   * @return skipThreatIntelligenceParams
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getSkipThreatIntelligenceParams() {
    return skipThreatIntelligenceParams;
  }

  public void setSkipThreatIntelligenceParams(Map<String, String> skipThreatIntelligenceParams) {
    this.skipThreatIntelligenceParams = skipThreatIntelligenceParams;
  }

  public ApplicationRequest skipThreatIntelligenceRegex(String skipThreatIntelligenceRegex) {
    this.skipThreatIntelligenceRegex = skipThreatIntelligenceRegex;
    return this;
  }

   /**
   * Get skipThreatIntelligenceRegex
   * @return skipThreatIntelligenceRegex
  **/
  @ApiModelProperty(value = "")
  public String getSkipThreatIntelligenceRegex() {
    return skipThreatIntelligenceRegex;
  }

  public void setSkipThreatIntelligenceRegex(String skipThreatIntelligenceRegex) {
    this.skipThreatIntelligenceRegex = skipThreatIntelligenceRegex;
  }

  public ApplicationRequest sourceCategory(SourceCategoryEnum sourceCategory) {
    this.sourceCategory = sourceCategory;
    return this;
  }

   /**
   * Get sourceCategory
   * @return sourceCategory
  **/
  @ApiModelProperty(value = "")
  public SourceCategoryEnum getSourceCategory() {
    return sourceCategory;
  }

  public void setSourceCategory(SourceCategoryEnum sourceCategory) {
    this.sourceCategory = sourceCategory;
  }

  public ApplicationRequest storeHashesInEthereum(Boolean storeHashesInEthereum) {
    this.storeHashesInEthereum = storeHashesInEthereum;
    return this;
  }

   /**
   * Get storeHashesInEthereum
   * @return storeHashesInEthereum
  **/
  @ApiModelProperty(value = "")
  public Boolean isStoreHashesInEthereum() {
    return storeHashesInEthereum;
  }

  public void setStoreHashesInEthereum(Boolean storeHashesInEthereum) {
    this.storeHashesInEthereum = storeHashesInEthereum;
  }

  public ApplicationRequest verificationFailureReportRecipientEmails(List<String> verificationFailureReportRecipientEmails) {
    this.verificationFailureReportRecipientEmails = verificationFailureReportRecipientEmails;
    return this;
  }

  public ApplicationRequest addVerificationFailureReportRecipientEmailsItem(String verificationFailureReportRecipientEmailsItem) {
    if (this.verificationFailureReportRecipientEmails == null) {
      this.verificationFailureReportRecipientEmails = new ArrayList<>();
    }
    this.verificationFailureReportRecipientEmails.add(verificationFailureReportRecipientEmailsItem);
    return this;
  }

   /**
   * Get verificationFailureReportRecipientEmails
   * @return verificationFailureReportRecipientEmails
  **/
  @ApiModelProperty(value = "")
  public List<String> getVerificationFailureReportRecipientEmails() {
    return verificationFailureReportRecipientEmails;
  }

  public void setVerificationFailureReportRecipientEmails(List<String> verificationFailureReportRecipientEmails) {
    this.verificationFailureReportRecipientEmails = verificationFailureReportRecipientEmails;
  }

  public ApplicationRequest verificationPeriodMinutes(Integer verificationPeriodMinutes) {
    this.verificationPeriodMinutes = verificationPeriodMinutes;
    return this;
  }

   /**
   * Get verificationPeriodMinutes
   * @return verificationPeriodMinutes
  **/
  @ApiModelProperty(value = "")
  public Integer getVerificationPeriodMinutes() {
    return verificationPeriodMinutes;
  }

  public void setVerificationPeriodMinutes(Integer verificationPeriodMinutes) {
    this.verificationPeriodMinutes = verificationPeriodMinutes;
  }

  public ApplicationRequest warnLevel(WarnLevelEnum warnLevel) {
    this.warnLevel = warnLevel;
    return this;
  }

   /**
   * Get warnLevel
   * @return warnLevel
  **/
  @ApiModelProperty(value = "")
  public WarnLevelEnum getWarnLevel() {
    return warnLevel;
  }

  public void setWarnLevel(WarnLevelEnum warnLevel) {
    this.warnLevel = warnLevel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationRequest applicationRequest = (ApplicationRequest) o;
    return Objects.equals(this.automaticBehaviorMonitoring, applicationRequest.automaticBehaviorMonitoring) &&
        Objects.equals(this.containsPersonalData, applicationRequest.containsPersonalData) &&
        Objects.equals(this.dataMaskingPatterns, applicationRequest.dataMaskingPatterns) &&
        Objects.equals(this.defaultAlertDestinations, applicationRequest.defaultAlertDestinations) &&
        Objects.equals(this.description, applicationRequest.description) &&
        Objects.equals(this.detailsTransformationScript, applicationRequest.detailsTransformationScript) &&
        Objects.equals(this.disabledThreatFeeds, applicationRequest.disabledThreatFeeds) &&
        Objects.equals(this.discardLogConditions, applicationRequest.discardLogConditions) &&
        Objects.equals(this.displayedDetailsFields, applicationRequest.displayedDetailsFields) &&
        Objects.equals(this.extractionOverrideEnabled, applicationRequest.extractionOverrideEnabled) &&
        Objects.equals(this.generateHashChain, applicationRequest.generateHashChain) &&
        Objects.equals(this.generateMerkleTree, applicationRequest.generateMerkleTree) &&
        Objects.equals(this.groupIds, applicationRequest.groupIds) &&
        Objects.equals(this.id, applicationRequest.id) &&
        Objects.equals(this.ipWhiteList, applicationRequest.ipWhiteList) &&
        Objects.equals(this.latestHashRecipientEmails, applicationRequest.latestHashRecipientEmails) &&
        Objects.equals(this.logGroupingEnabled, applicationRequest.logGroupingEnabled) &&
        Objects.equals(this.logLevelRegexes, applicationRequest.logLevelRegexes) &&
        Objects.equals(this.metadataExtractionPaths, applicationRequest.metadataExtractionPaths) &&
        Objects.equals(this.name, applicationRequest.name) &&
        Objects.equals(this.newThreatIntelAlertPeriodHours, applicationRequest.newThreatIntelAlertPeriodHours) &&
        Objects.equals(this.openDataAnonymizationRegexes, applicationRequest.openDataAnonymizationRegexes) &&
        Objects.equals(this.openDataAnonymizeBodyFields, applicationRequest.openDataAnonymizeBodyFields) &&
        Objects.equals(this.openDataEnabled, applicationRequest.openDataEnabled) &&
        Objects.equals(this.openDataWhitelistRegexes, applicationRequest.openDataWhitelistRegexes) &&
        Objects.equals(this.partialVerificationPeriodMinutes, applicationRequest.partialVerificationPeriodMinutes) &&
        Objects.equals(this.propertiesForIdenticalEntries, applicationRequest.propertiesForIdenticalEntries) &&
        Objects.equals(this.retentionDays, applicationRequest.retentionDays) &&
        Objects.equals(this.riskLevel, applicationRequest.riskLevel) &&
        Objects.equals(this.signatureVerificationPublicKeys, applicationRequest.signatureVerificationPublicKeys) &&
        Objects.equals(this.skipThreatIntelligenceParams, applicationRequest.skipThreatIntelligenceParams) &&
        Objects.equals(this.skipThreatIntelligenceRegex, applicationRequest.skipThreatIntelligenceRegex) &&
        Objects.equals(this.sourceCategory, applicationRequest.sourceCategory) &&
        Objects.equals(this.storeHashesInEthereum, applicationRequest.storeHashesInEthereum) &&
        Objects.equals(this.verificationFailureReportRecipientEmails, applicationRequest.verificationFailureReportRecipientEmails) &&
        Objects.equals(this.verificationPeriodMinutes, applicationRequest.verificationPeriodMinutes) &&
        Objects.equals(this.warnLevel, applicationRequest.warnLevel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(automaticBehaviorMonitoring, containsPersonalData, dataMaskingPatterns, defaultAlertDestinations, description, detailsTransformationScript, disabledThreatFeeds, discardLogConditions, displayedDetailsFields, extractionOverrideEnabled, generateHashChain, generateMerkleTree, groupIds, id, ipWhiteList, latestHashRecipientEmails, logGroupingEnabled, logLevelRegexes, metadataExtractionPaths, name, newThreatIntelAlertPeriodHours, openDataAnonymizationRegexes, openDataAnonymizeBodyFields, openDataEnabled, openDataWhitelistRegexes, partialVerificationPeriodMinutes, propertiesForIdenticalEntries, retentionDays, riskLevel, signatureVerificationPublicKeys, skipThreatIntelligenceParams, skipThreatIntelligenceRegex, sourceCategory, storeHashesInEthereum, verificationFailureReportRecipientEmails, verificationPeriodMinutes, warnLevel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationRequest {\n");
    
    sb.append("    automaticBehaviorMonitoring: ").append(toIndentedString(automaticBehaviorMonitoring)).append("\n");
    sb.append("    containsPersonalData: ").append(toIndentedString(containsPersonalData)).append("\n");
    sb.append("    dataMaskingPatterns: ").append(toIndentedString(dataMaskingPatterns)).append("\n");
    sb.append("    defaultAlertDestinations: ").append(toIndentedString(defaultAlertDestinations)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    detailsTransformationScript: ").append(toIndentedString(detailsTransformationScript)).append("\n");
    sb.append("    disabledThreatFeeds: ").append(toIndentedString(disabledThreatFeeds)).append("\n");
    sb.append("    discardLogConditions: ").append(toIndentedString(discardLogConditions)).append("\n");
    sb.append("    displayedDetailsFields: ").append(toIndentedString(displayedDetailsFields)).append("\n");
    sb.append("    extractionOverrideEnabled: ").append(toIndentedString(extractionOverrideEnabled)).append("\n");
    sb.append("    generateHashChain: ").append(toIndentedString(generateHashChain)).append("\n");
    sb.append("    generateMerkleTree: ").append(toIndentedString(generateMerkleTree)).append("\n");
    sb.append("    groupIds: ").append(toIndentedString(groupIds)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ipWhiteList: ").append(toIndentedString(ipWhiteList)).append("\n");
    sb.append("    latestHashRecipientEmails: ").append(toIndentedString(latestHashRecipientEmails)).append("\n");
    sb.append("    logGroupingEnabled: ").append(toIndentedString(logGroupingEnabled)).append("\n");
    sb.append("    logLevelRegexes: ").append(toIndentedString(logLevelRegexes)).append("\n");
    sb.append("    metadataExtractionPaths: ").append(toIndentedString(metadataExtractionPaths)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    newThreatIntelAlertPeriodHours: ").append(toIndentedString(newThreatIntelAlertPeriodHours)).append("\n");
    sb.append("    openDataAnonymizationRegexes: ").append(toIndentedString(openDataAnonymizationRegexes)).append("\n");
    sb.append("    openDataAnonymizeBodyFields: ").append(toIndentedString(openDataAnonymizeBodyFields)).append("\n");
    sb.append("    openDataEnabled: ").append(toIndentedString(openDataEnabled)).append("\n");
    sb.append("    openDataWhitelistRegexes: ").append(toIndentedString(openDataWhitelistRegexes)).append("\n");
    sb.append("    partialVerificationPeriodMinutes: ").append(toIndentedString(partialVerificationPeriodMinutes)).append("\n");
    sb.append("    propertiesForIdenticalEntries: ").append(toIndentedString(propertiesForIdenticalEntries)).append("\n");
    sb.append("    retentionDays: ").append(toIndentedString(retentionDays)).append("\n");
    sb.append("    riskLevel: ").append(toIndentedString(riskLevel)).append("\n");
    sb.append("    signatureVerificationPublicKeys: ").append(toIndentedString(signatureVerificationPublicKeys)).append("\n");
    sb.append("    skipThreatIntelligenceParams: ").append(toIndentedString(skipThreatIntelligenceParams)).append("\n");
    sb.append("    skipThreatIntelligenceRegex: ").append(toIndentedString(skipThreatIntelligenceRegex)).append("\n");
    sb.append("    sourceCategory: ").append(toIndentedString(sourceCategory)).append("\n");
    sb.append("    storeHashesInEthereum: ").append(toIndentedString(storeHashesInEthereum)).append("\n");
    sb.append("    verificationFailureReportRecipientEmails: ").append(toIndentedString(verificationFailureReportRecipientEmails)).append("\n");
    sb.append("    verificationPeriodMinutes: ").append(toIndentedString(verificationPeriodMinutes)).append("\n");
    sb.append("    warnLevel: ").append(toIndentedString(warnLevel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

