/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ByteBuffer
 */

public class ByteBuffer {
  @JsonProperty("char")
  private String _char = null;

  @JsonProperty("direct")
  private Boolean direct = null;

  @JsonProperty("double")
  private Double _double = null;

  @JsonProperty("float")
  private Float _float = null;

  @JsonProperty("int")
  private Integer _int = null;

  @JsonProperty("long")
  private Long _long = null;

  @JsonProperty("readOnly")
  private Boolean readOnly = null;

  @JsonProperty("short")
  private Integer _short = null;

  public ByteBuffer _char(String _char) {
    this._char = _char;
    return this;
  }

   /**
   * Get _char
   * @return _char
  **/
  @ApiModelProperty(value = "")
  public String getChar() {
    return _char;
  }

  public void setChar(String _char) {
    this._char = _char;
  }

  public ByteBuffer direct(Boolean direct) {
    this.direct = direct;
    return this;
  }

   /**
   * Get direct
   * @return direct
  **/
  @ApiModelProperty(value = "")
  public Boolean isDirect() {
    return direct;
  }

  public void setDirect(Boolean direct) {
    this.direct = direct;
  }

  public ByteBuffer _double(Double _double) {
    this._double = _double;
    return this;
  }

   /**
   * Get _double
   * @return _double
  **/
  @ApiModelProperty(value = "")
  public Double getDouble() {
    return _double;
  }

  public void setDouble(Double _double) {
    this._double = _double;
  }

  public ByteBuffer _float(Float _float) {
    this._float = _float;
    return this;
  }

   /**
   * Get _float
   * @return _float
  **/
  @ApiModelProperty(value = "")
  public Float getFloat() {
    return _float;
  }

  public void setFloat(Float _float) {
    this._float = _float;
  }

  public ByteBuffer _int(Integer _int) {
    this._int = _int;
    return this;
  }

   /**
   * Get _int
   * @return _int
  **/
  @ApiModelProperty(value = "")
  public Integer getInt() {
    return _int;
  }

  public void setInt(Integer _int) {
    this._int = _int;
  }

  public ByteBuffer _long(Long _long) {
    this._long = _long;
    return this;
  }

   /**
   * Get _long
   * @return _long
  **/
  @ApiModelProperty(value = "")
  public Long getLong() {
    return _long;
  }

  public void setLong(Long _long) {
    this._long = _long;
  }

  public ByteBuffer readOnly(Boolean readOnly) {
    this.readOnly = readOnly;
    return this;
  }

   /**
   * Get readOnly
   * @return readOnly
  **/
  @ApiModelProperty(value = "")
  public Boolean isReadOnly() {
    return readOnly;
  }

  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }

  public ByteBuffer _short(Integer _short) {
    this._short = _short;
    return this;
  }

   /**
   * Get _short
   * @return _short
  **/
  @ApiModelProperty(value = "")
  public Integer getShort() {
    return _short;
  }

  public void setShort(Integer _short) {
    this._short = _short;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ByteBuffer byteBuffer = (ByteBuffer) o;
    return Objects.equals(this._char, byteBuffer._char) &&
        Objects.equals(this.direct, byteBuffer.direct) &&
        Objects.equals(this._double, byteBuffer._double) &&
        Objects.equals(this._float, byteBuffer._float) &&
        Objects.equals(this._int, byteBuffer._int) &&
        Objects.equals(this._long, byteBuffer._long) &&
        Objects.equals(this.readOnly, byteBuffer.readOnly) &&
        Objects.equals(this._short, byteBuffer._short);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_char, direct, _double, _float, _int, _long, readOnly, _short);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ByteBuffer {\n");
    
    sb.append("    _char: ").append(toIndentedString(_char)).append("\n");
    sb.append("    direct: ").append(toIndentedString(direct)).append("\n");
    sb.append("    _double: ").append(toIndentedString(_double)).append("\n");
    sb.append("    _float: ").append(toIndentedString(_float)).append("\n");
    sb.append("    _int: ").append(toIndentedString(_int)).append("\n");
    sb.append("    _long: ").append(toIndentedString(_long)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    _short: ").append(toIndentedString(_short)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

