/*
 * RESTful API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CCPAResult
 */

public class CCPAResult {
  @JsonProperty("additionalDetails")
  private String additionalDetails = null;

  @JsonProperty("consumerId")
  private String consumerId = null;

  @JsonProperty("consumerName")
  private String consumerName = null;

  @JsonProperty("requestEntryId")
  private String requestEntryId = null;

  @JsonProperty("result")
  private String result = null;

  @JsonProperty("timestamp")
  private Long timestamp = null;

  public CCPAResult additionalDetails(String additionalDetails) {
    this.additionalDetails = additionalDetails;
    return this;
  }

   /**
   * Get additionalDetails
   * @return additionalDetails
  **/
  @ApiModelProperty(value = "")
  public String getAdditionalDetails() {
    return additionalDetails;
  }

  public void setAdditionalDetails(String additionalDetails) {
    this.additionalDetails = additionalDetails;
  }

  public CCPAResult consumerId(String consumerId) {
    this.consumerId = consumerId;
    return this;
  }

   /**
   * Get consumerId
   * @return consumerId
  **/
  @ApiModelProperty(value = "")
  public String getConsumerId() {
    return consumerId;
  }

  public void setConsumerId(String consumerId) {
    this.consumerId = consumerId;
  }

  public CCPAResult consumerName(String consumerName) {
    this.consumerName = consumerName;
    return this;
  }

   /**
   * Get consumerName
   * @return consumerName
  **/
  @ApiModelProperty(value = "")
  public String getConsumerName() {
    return consumerName;
  }

  public void setConsumerName(String consumerName) {
    this.consumerName = consumerName;
  }

  public CCPAResult requestEntryId(String requestEntryId) {
    this.requestEntryId = requestEntryId;
    return this;
  }

   /**
   * Get requestEntryId
   * @return requestEntryId
  **/
  @ApiModelProperty(value = "")
  public String getRequestEntryId() {
    return requestEntryId;
  }

  public void setRequestEntryId(String requestEntryId) {
    this.requestEntryId = requestEntryId;
  }

  public CCPAResult result(String result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }

  public CCPAResult timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CCPAResult ccPAResult = (CCPAResult) o;
    return Objects.equals(this.additionalDetails, ccPAResult.additionalDetails) &&
        Objects.equals(this.consumerId, ccPAResult.consumerId) &&
        Objects.equals(this.consumerName, ccPAResult.consumerName) &&
        Objects.equals(this.requestEntryId, ccPAResult.requestEntryId) &&
        Objects.equals(this.result, ccPAResult.result) &&
        Objects.equals(this.timestamp, ccPAResult.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalDetails, consumerId, consumerName, requestEntryId, result, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CCPAResult {\n");
    
    sb.append("    additionalDetails: ").append(toIndentedString(additionalDetails)).append("\n");
    sb.append("    consumerId: ").append(toIndentedString(consumerId)).append("\n");
    sb.append("    consumerName: ").append(toIndentedString(consumerName)).append("\n");
    sb.append("    requestEntryId: ").append(toIndentedString(requestEntryId)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

