/*
 * RESTful API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.logsentinel.model.ConnectorStatusDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * CollectorStatusDto
 */

public class CollectorStatusDto {
  @JsonProperty("collectorId")
  private UUID collectorId = null;

  @JsonProperty("connectorStatus")
  private List<ConnectorStatusDto> connectorStatus = null;

  public CollectorStatusDto collectorId(UUID collectorId) {
    this.collectorId = collectorId;
    return this;
  }

   /**
   * Get collectorId
   * @return collectorId
  **/
  @ApiModelProperty(value = "")
  public UUID getCollectorId() {
    return collectorId;
  }

  public void setCollectorId(UUID collectorId) {
    this.collectorId = collectorId;
  }

  public CollectorStatusDto connectorStatus(List<ConnectorStatusDto> connectorStatus) {
    this.connectorStatus = connectorStatus;
    return this;
  }

  public CollectorStatusDto addConnectorStatusItem(ConnectorStatusDto connectorStatusItem) {
    if (this.connectorStatus == null) {
      this.connectorStatus = new ArrayList<>();
    }
    this.connectorStatus.add(connectorStatusItem);
    return this;
  }

   /**
   * Get connectorStatus
   * @return connectorStatus
  **/
  @ApiModelProperty(value = "")
  public List<ConnectorStatusDto> getConnectorStatus() {
    return connectorStatus;
  }

  public void setConnectorStatus(List<ConnectorStatusDto> connectorStatus) {
    this.connectorStatus = connectorStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CollectorStatusDto collectorStatusDto = (CollectorStatusDto) o;
    return Objects.equals(this.collectorId, collectorStatusDto.collectorId) &&
        Objects.equals(this.connectorStatus, collectorStatusDto.connectorStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collectorId, connectorStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CollectorStatusDto {\n");
    
    sb.append("    collectorId: ").append(toIndentedString(collectorId)).append("\n");
    sb.append("    connectorStatus: ").append(toIndentedString(connectorStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

