/*
 * RESTful API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ExternalDetails
 */

public class ExternalDetails {
  @JsonProperty("canonicalHostname")
  private String canonicalHostname = null;

  @JsonProperty("threatIntelDetails")
  private List<String> threatIntelDetails = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    IPV4("IPV4"),
    
    IPV6("IPV6"),
    
    EMAIL_ADDRESS("EMAIL_ADDRESS"),
    
    DOMAIN("DOMAIN"),
    
    URL("URL"),
    
    FILE_HASH("FILE_HASH");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("value")
  private String value = null;

  @JsonProperty("whoisParams")
  private Map<String, String> whoisParams = null;

  @JsonProperty("whoisRaw")
  private String whoisRaw = null;

  public ExternalDetails canonicalHostname(String canonicalHostname) {
    this.canonicalHostname = canonicalHostname;
    return this;
  }

   /**
   * Get canonicalHostname
   * @return canonicalHostname
  **/
  @ApiModelProperty(value = "")
  public String getCanonicalHostname() {
    return canonicalHostname;
  }

  public void setCanonicalHostname(String canonicalHostname) {
    this.canonicalHostname = canonicalHostname;
  }

  public ExternalDetails threatIntelDetails(List<String> threatIntelDetails) {
    this.threatIntelDetails = threatIntelDetails;
    return this;
  }

  public ExternalDetails addThreatIntelDetailsItem(String threatIntelDetailsItem) {
    if (this.threatIntelDetails == null) {
      this.threatIntelDetails = new ArrayList<>();
    }
    this.threatIntelDetails.add(threatIntelDetailsItem);
    return this;
  }

   /**
   * Get threatIntelDetails
   * @return threatIntelDetails
  **/
  @ApiModelProperty(value = "")
  public List<String> getThreatIntelDetails() {
    return threatIntelDetails;
  }

  public void setThreatIntelDetails(List<String> threatIntelDetails) {
    this.threatIntelDetails = threatIntelDetails;
  }

  public ExternalDetails type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public ExternalDetails value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public ExternalDetails whoisParams(Map<String, String> whoisParams) {
    this.whoisParams = whoisParams;
    return this;
  }

  public ExternalDetails putWhoisParamsItem(String key, String whoisParamsItem) {
    if (this.whoisParams == null) {
      this.whoisParams = new HashMap<>();
    }
    this.whoisParams.put(key, whoisParamsItem);
    return this;
  }

   /**
   * Get whoisParams
   * @return whoisParams
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getWhoisParams() {
    return whoisParams;
  }

  public void setWhoisParams(Map<String, String> whoisParams) {
    this.whoisParams = whoisParams;
  }

  public ExternalDetails whoisRaw(String whoisRaw) {
    this.whoisRaw = whoisRaw;
    return this;
  }

   /**
   * Get whoisRaw
   * @return whoisRaw
  **/
  @ApiModelProperty(value = "")
  public String getWhoisRaw() {
    return whoisRaw;
  }

  public void setWhoisRaw(String whoisRaw) {
    this.whoisRaw = whoisRaw;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalDetails externalDetails = (ExternalDetails) o;
    return Objects.equals(this.canonicalHostname, externalDetails.canonicalHostname) &&
        Objects.equals(this.threatIntelDetails, externalDetails.threatIntelDetails) &&
        Objects.equals(this.type, externalDetails.type) &&
        Objects.equals(this.value, externalDetails.value) &&
        Objects.equals(this.whoisParams, externalDetails.whoisParams) &&
        Objects.equals(this.whoisRaw, externalDetails.whoisRaw);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canonicalHostname, threatIntelDetails, type, value, whoisParams, whoisRaw);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalDetails {\n");
    
    sb.append("    canonicalHostname: ").append(toIndentedString(canonicalHostname)).append("\n");
    sb.append("    threatIntelDetails: ").append(toIndentedString(threatIntelDetails)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    whoisParams: ").append(toIndentedString(whoisParams)).append("\n");
    sb.append("    whoisRaw: ").append(toIndentedString(whoisRaw)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

