/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GDPRResult
 */

public class GDPRResult {
  @JsonProperty("additionalDetails")
  private String additionalDetails = null;

  @JsonProperty("dataSubjectId")
  private String dataSubjectId = null;

  @JsonProperty("dataSubjectName")
  private String dataSubjectName = null;

  @JsonProperty("requestEntryId")
  private String requestEntryId = null;

  @JsonProperty("result")
  private String result = null;

  @JsonProperty("timestamp")
  private Long timestamp = null;

  public GDPRResult additionalDetails(String additionalDetails) {
    this.additionalDetails = additionalDetails;
    return this;
  }

   /**
   * Get additionalDetails
   * @return additionalDetails
  **/
  @ApiModelProperty(value = "")
  public String getAdditionalDetails() {
    return additionalDetails;
  }

  public void setAdditionalDetails(String additionalDetails) {
    this.additionalDetails = additionalDetails;
  }

  public GDPRResult dataSubjectId(String dataSubjectId) {
    this.dataSubjectId = dataSubjectId;
    return this;
  }

   /**
   * Get dataSubjectId
   * @return dataSubjectId
  **/
  @ApiModelProperty(value = "")
  public String getDataSubjectId() {
    return dataSubjectId;
  }

  public void setDataSubjectId(String dataSubjectId) {
    this.dataSubjectId = dataSubjectId;
  }

  public GDPRResult dataSubjectName(String dataSubjectName) {
    this.dataSubjectName = dataSubjectName;
    return this;
  }

   /**
   * Get dataSubjectName
   * @return dataSubjectName
  **/
  @ApiModelProperty(value = "")
  public String getDataSubjectName() {
    return dataSubjectName;
  }

  public void setDataSubjectName(String dataSubjectName) {
    this.dataSubjectName = dataSubjectName;
  }

  public GDPRResult requestEntryId(String requestEntryId) {
    this.requestEntryId = requestEntryId;
    return this;
  }

   /**
   * Get requestEntryId
   * @return requestEntryId
  **/
  @ApiModelProperty(value = "")
  public String getRequestEntryId() {
    return requestEntryId;
  }

  public void setRequestEntryId(String requestEntryId) {
    this.requestEntryId = requestEntryId;
  }

  public GDPRResult result(String result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }

  public GDPRResult timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GDPRResult gdPRResult = (GDPRResult) o;
    return Objects.equals(this.additionalDetails, gdPRResult.additionalDetails) &&
        Objects.equals(this.dataSubjectId, gdPRResult.dataSubjectId) &&
        Objects.equals(this.dataSubjectName, gdPRResult.dataSubjectName) &&
        Objects.equals(this.requestEntryId, gdPRResult.requestEntryId) &&
        Objects.equals(this.result, gdPRResult.result) &&
        Objects.equals(this.timestamp, gdPRResult.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalDetails, dataSubjectId, dataSubjectName, requestEntryId, result, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GDPRResult {\n");
    
    sb.append("    additionalDetails: ").append(toIndentedString(additionalDetails)).append("\n");
    sb.append("    dataSubjectId: ").append(toIndentedString(dataSubjectId)).append("\n");
    sb.append("    dataSubjectName: ").append(toIndentedString(dataSubjectName)).append("\n");
    sb.append("    requestEntryId: ").append(toIndentedString(requestEntryId)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

