/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * IPDetails
 */

public class IPDetails {
  @JsonProperty("badDomainScore")
  private String badDomainScore = null;

  @JsonProperty("badIpBlacklists")
  private List<String> badIpBlacklists = null;

  @JsonProperty("badIpScore")
  private String badIpScore = null;

  @JsonProperty("city")
  private String city = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("countryNamesEn")
  private String countryNamesEn = null;

  @JsonProperty("historyScore")
  private String historyScore = null;

  @JsonProperty("hostname")
  private String hostname = null;

  @JsonProperty("ipAddress")
  private String ipAddress = null;

  @JsonProperty("latitude")
  private String latitude = null;

  @JsonProperty("longitude")
  private String longitude = null;

  @JsonProperty("score")
  private String score = null;

  @JsonProperty("sourceIpBlacklist")
  private List<String> sourceIpBlacklist = null;

  @JsonProperty("sourceIpIsQuarantined")
  private String sourceIpIsQuarantined = null;

  @JsonProperty("sourceIpScore")
  private String sourceIpScore = null;

  public IPDetails badDomainScore(String badDomainScore) {
    this.badDomainScore = badDomainScore;
    return this;
  }

   /**
   * Get badDomainScore
   * @return badDomainScore
  **/
  @ApiModelProperty(value = "")
  public String getBadDomainScore() {
    return badDomainScore;
  }

  public void setBadDomainScore(String badDomainScore) {
    this.badDomainScore = badDomainScore;
  }

  public IPDetails badIpBlacklists(List<String> badIpBlacklists) {
    this.badIpBlacklists = badIpBlacklists;
    return this;
  }

  public IPDetails addBadIpBlacklistsItem(String badIpBlacklistsItem) {
    if (this.badIpBlacklists == null) {
      this.badIpBlacklists = new ArrayList<>();
    }
    this.badIpBlacklists.add(badIpBlacklistsItem);
    return this;
  }

   /**
   * Get badIpBlacklists
   * @return badIpBlacklists
  **/
  @ApiModelProperty(value = "")
  public List<String> getBadIpBlacklists() {
    return badIpBlacklists;
  }

  public void setBadIpBlacklists(List<String> badIpBlacklists) {
    this.badIpBlacklists = badIpBlacklists;
  }

  public IPDetails badIpScore(String badIpScore) {
    this.badIpScore = badIpScore;
    return this;
  }

   /**
   * Get badIpScore
   * @return badIpScore
  **/
  @ApiModelProperty(value = "")
  public String getBadIpScore() {
    return badIpScore;
  }

  public void setBadIpScore(String badIpScore) {
    this.badIpScore = badIpScore;
  }

  public IPDetails city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public IPDetails country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public IPDetails countryNamesEn(String countryNamesEn) {
    this.countryNamesEn = countryNamesEn;
    return this;
  }

   /**
   * Get countryNamesEn
   * @return countryNamesEn
  **/
  @ApiModelProperty(value = "")
  public String getCountryNamesEn() {
    return countryNamesEn;
  }

  public void setCountryNamesEn(String countryNamesEn) {
    this.countryNamesEn = countryNamesEn;
  }

  public IPDetails historyScore(String historyScore) {
    this.historyScore = historyScore;
    return this;
  }

   /**
   * Get historyScore
   * @return historyScore
  **/
  @ApiModelProperty(value = "")
  public String getHistoryScore() {
    return historyScore;
  }

  public void setHistoryScore(String historyScore) {
    this.historyScore = historyScore;
  }

  public IPDetails hostname(String hostname) {
    this.hostname = hostname;
    return this;
  }

   /**
   * Get hostname
   * @return hostname
  **/
  @ApiModelProperty(value = "")
  public String getHostname() {
    return hostname;
  }

  public void setHostname(String hostname) {
    this.hostname = hostname;
  }

  public IPDetails ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * Get ipAddress
   * @return ipAddress
  **/
  @ApiModelProperty(value = "")
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  public IPDetails latitude(String latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @ApiModelProperty(value = "")
  public String getLatitude() {
    return latitude;
  }

  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }

  public IPDetails longitude(String longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @ApiModelProperty(value = "")
  public String getLongitude() {
    return longitude;
  }

  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }

  public IPDetails score(String score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  @ApiModelProperty(value = "")
  public String getScore() {
    return score;
  }

  public void setScore(String score) {
    this.score = score;
  }

  public IPDetails sourceIpBlacklist(List<String> sourceIpBlacklist) {
    this.sourceIpBlacklist = sourceIpBlacklist;
    return this;
  }

  public IPDetails addSourceIpBlacklistItem(String sourceIpBlacklistItem) {
    if (this.sourceIpBlacklist == null) {
      this.sourceIpBlacklist = new ArrayList<>();
    }
    this.sourceIpBlacklist.add(sourceIpBlacklistItem);
    return this;
  }

   /**
   * Get sourceIpBlacklist
   * @return sourceIpBlacklist
  **/
  @ApiModelProperty(value = "")
  public List<String> getSourceIpBlacklist() {
    return sourceIpBlacklist;
  }

  public void setSourceIpBlacklist(List<String> sourceIpBlacklist) {
    this.sourceIpBlacklist = sourceIpBlacklist;
  }

  public IPDetails sourceIpIsQuarantined(String sourceIpIsQuarantined) {
    this.sourceIpIsQuarantined = sourceIpIsQuarantined;
    return this;
  }

   /**
   * Get sourceIpIsQuarantined
   * @return sourceIpIsQuarantined
  **/
  @ApiModelProperty(value = "")
  public String getSourceIpIsQuarantined() {
    return sourceIpIsQuarantined;
  }

  public void setSourceIpIsQuarantined(String sourceIpIsQuarantined) {
    this.sourceIpIsQuarantined = sourceIpIsQuarantined;
  }

  public IPDetails sourceIpScore(String sourceIpScore) {
    this.sourceIpScore = sourceIpScore;
    return this;
  }

   /**
   * Get sourceIpScore
   * @return sourceIpScore
  **/
  @ApiModelProperty(value = "")
  public String getSourceIpScore() {
    return sourceIpScore;
  }

  public void setSourceIpScore(String sourceIpScore) {
    this.sourceIpScore = sourceIpScore;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IPDetails ipDetails = (IPDetails) o;
    return Objects.equals(this.badDomainScore, ipDetails.badDomainScore) &&
        Objects.equals(this.badIpBlacklists, ipDetails.badIpBlacklists) &&
        Objects.equals(this.badIpScore, ipDetails.badIpScore) &&
        Objects.equals(this.city, ipDetails.city) &&
        Objects.equals(this.country, ipDetails.country) &&
        Objects.equals(this.countryNamesEn, ipDetails.countryNamesEn) &&
        Objects.equals(this.historyScore, ipDetails.historyScore) &&
        Objects.equals(this.hostname, ipDetails.hostname) &&
        Objects.equals(this.ipAddress, ipDetails.ipAddress) &&
        Objects.equals(this.latitude, ipDetails.latitude) &&
        Objects.equals(this.longitude, ipDetails.longitude) &&
        Objects.equals(this.score, ipDetails.score) &&
        Objects.equals(this.sourceIpBlacklist, ipDetails.sourceIpBlacklist) &&
        Objects.equals(this.sourceIpIsQuarantined, ipDetails.sourceIpIsQuarantined) &&
        Objects.equals(this.sourceIpScore, ipDetails.sourceIpScore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(badDomainScore, badIpBlacklists, badIpScore, city, country, countryNamesEn, historyScore, hostname, ipAddress, latitude, longitude, score, sourceIpBlacklist, sourceIpIsQuarantined, sourceIpScore);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IPDetails {\n");
    
    sb.append("    badDomainScore: ").append(toIndentedString(badDomainScore)).append("\n");
    sb.append("    badIpBlacklists: ").append(toIndentedString(badIpBlacklists)).append("\n");
    sb.append("    badIpScore: ").append(toIndentedString(badIpScore)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    countryNamesEn: ").append(toIndentedString(countryNamesEn)).append("\n");
    sb.append("    historyScore: ").append(toIndentedString(historyScore)).append("\n");
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    sourceIpBlacklist: ").append(toIndentedString(sourceIpBlacklist)).append("\n");
    sb.append("    sourceIpIsQuarantined: ").append(toIndentedString(sourceIpIsQuarantined)).append("\n");
    sb.append("    sourceIpScore: ").append(toIndentedString(sourceIpScore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

