/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * LogResponse
 */

@JsonIgnoreProperties(ignoreUnknown = true)
public class LogResponse {
  @JsonProperty("failedLogIndexes")
  private List<Integer> failedLogIndexes = null;

  @JsonProperty("lastKnownHash")
  private String lastKnownHash = null;

  @JsonProperty("logEntryId")
  private String logEntryId = null;

  @JsonProperty("standaloneHash")
  private String standaloneHash = null;

  public LogResponse failedLogIndexes(List<Integer> failedLogIndexes) {
    this.failedLogIndexes = failedLogIndexes;
    return this;
  }

  public LogResponse addFailedLogIndexesItem(Integer failedLogIndexesItem) {
    if (this.failedLogIndexes == null) {
      this.failedLogIndexes = new ArrayList<>();
    }
    this.failedLogIndexes.add(failedLogIndexesItem);
    return this;
  }

   /**
   * Get failedLogIndexes
   * @return failedLogIndexes
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getFailedLogIndexes() {
    return failedLogIndexes;
  }

  public void setFailedLogIndexes(List<Integer> failedLogIndexes) {
    this.failedLogIndexes = failedLogIndexes;
  }

  public LogResponse lastKnownHash(String lastKnownHash) {
    this.lastKnownHash = lastKnownHash;
    return this;
  }

   /**
   * Get lastKnownHash
   * @return lastKnownHash
  **/
  @ApiModelProperty(value = "")
  public String getLastKnownHash() {
    return lastKnownHash;
  }

  public void setLastKnownHash(String lastKnownHash) {
    this.lastKnownHash = lastKnownHash;
  }

  public LogResponse logEntryId(String logEntryId) {
    this.logEntryId = logEntryId;
    return this;
  }

   /**
   * Get logEntryId
   * @return logEntryId
  **/
  @ApiModelProperty(value = "")
  public String getLogEntryId() {
    return logEntryId;
  }

  public void setLogEntryId(String logEntryId) {
    this.logEntryId = logEntryId;
  }

  public LogResponse standaloneHash(String standaloneHash) {
    this.standaloneHash = standaloneHash;
    return this;
  }

   /**
   * Get standaloneHash
   * @return standaloneHash
  **/
  @ApiModelProperty(value = "")
  public String getStandaloneHash() {
    return standaloneHash;
  }

  public void setStandaloneHash(String standaloneHash) {
    this.standaloneHash = standaloneHash;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogResponse logResponse = (LogResponse) o;
    return Objects.equals(this.failedLogIndexes, logResponse.failedLogIndexes) &&
        Objects.equals(this.lastKnownHash, logResponse.lastKnownHash) &&
        Objects.equals(this.logEntryId, logResponse.logEntryId) &&
        Objects.equals(this.standaloneHash, logResponse.standaloneHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(failedLogIndexes, lastKnownHash, logEntryId, standaloneHash);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogResponse {\n");
    
    sb.append("    failedLogIndexes: ").append(toIndentedString(failedLogIndexes)).append("\n");
    sb.append("    lastKnownHash: ").append(toIndentedString(lastKnownHash)).append("\n");
    sb.append("    logEntryId: ").append(toIndentedString(logEntryId)).append("\n");
    sb.append("    standaloneHash: ").append(toIndentedString(standaloneHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

