/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;

/**
 * MachineLearningSettings
 */

public class MachineLearningSettings {
  @JsonProperty("anomalyDetectionEnabled")
  private Boolean anomalyDetectionEnabled = null;

  @JsonProperty("anomalyDetectionEnabledDate")
  private OffsetDateTime anomalyDetectionEnabledDate = null;

  @JsonProperty("includeEntityFields")
  private Boolean includeEntityFields = null;

  /**
   * Gets or Sets timestampField
   */
  public enum TimestampFieldEnum {
    RECEIVED("RECEIVED"),
    
    ORIGINAL("ORIGINAL");

    private String value;

    TimestampFieldEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TimestampFieldEnum fromValue(String text) {
      for (TimestampFieldEnum b : TimestampFieldEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("timestampField")
  private TimestampFieldEnum timestampField = null;

  public MachineLearningSettings anomalyDetectionEnabled(Boolean anomalyDetectionEnabled) {
    this.anomalyDetectionEnabled = anomalyDetectionEnabled;
    return this;
  }

   /**
   * Get anomalyDetectionEnabled
   * @return anomalyDetectionEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isAnomalyDetectionEnabled() {
    return anomalyDetectionEnabled;
  }

  public void setAnomalyDetectionEnabled(Boolean anomalyDetectionEnabled) {
    this.anomalyDetectionEnabled = anomalyDetectionEnabled;
  }

  public MachineLearningSettings anomalyDetectionEnabledDate(OffsetDateTime anomalyDetectionEnabledDate) {
    this.anomalyDetectionEnabledDate = anomalyDetectionEnabledDate;
    return this;
  }

   /**
   * Get anomalyDetectionEnabledDate
   * @return anomalyDetectionEnabledDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getAnomalyDetectionEnabledDate() {
    return anomalyDetectionEnabledDate;
  }

  public void setAnomalyDetectionEnabledDate(OffsetDateTime anomalyDetectionEnabledDate) {
    this.anomalyDetectionEnabledDate = anomalyDetectionEnabledDate;
  }

  public MachineLearningSettings includeEntityFields(Boolean includeEntityFields) {
    this.includeEntityFields = includeEntityFields;
    return this;
  }

   /**
   * Get includeEntityFields
   * @return includeEntityFields
  **/
  @ApiModelProperty(value = "")
  public Boolean isIncludeEntityFields() {
    return includeEntityFields;
  }

  public void setIncludeEntityFields(Boolean includeEntityFields) {
    this.includeEntityFields = includeEntityFields;
  }

  public MachineLearningSettings timestampField(TimestampFieldEnum timestampField) {
    this.timestampField = timestampField;
    return this;
  }

   /**
   * Get timestampField
   * @return timestampField
  **/
  @ApiModelProperty(value = "")
  public TimestampFieldEnum getTimestampField() {
    return timestampField;
  }

  public void setTimestampField(TimestampFieldEnum timestampField) {
    this.timestampField = timestampField;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MachineLearningSettings machineLearningSettings = (MachineLearningSettings) o;
    return Objects.equals(this.anomalyDetectionEnabled, machineLearningSettings.anomalyDetectionEnabled) &&
        Objects.equals(this.anomalyDetectionEnabledDate, machineLearningSettings.anomalyDetectionEnabledDate) &&
        Objects.equals(this.includeEntityFields, machineLearningSettings.includeEntityFields) &&
        Objects.equals(this.timestampField, machineLearningSettings.timestampField);
  }

  @Override
  public int hashCode() {
    return Objects.hash(anomalyDetectionEnabled, anomalyDetectionEnabledDate, includeEntityFields, timestampField);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MachineLearningSettings {\n");
    
    sb.append("    anomalyDetectionEnabled: ").append(toIndentedString(anomalyDetectionEnabled)).append("\n");
    sb.append("    anomalyDetectionEnabledDate: ").append(toIndentedString(anomalyDetectionEnabledDate)).append("\n");
    sb.append("    includeEntityFields: ").append(toIndentedString(includeEntityFields)).append("\n");
    sb.append("    timestampField: ").append(toIndentedString(timestampField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

