/*
 * RESTful API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * SavedSearch
 */

public class SavedSearch {
  @JsonProperty("applicationIds")
  private List<UUID> applicationIds = null;

  @JsonProperty("created")
  private LocalDateTime created = null;

  @JsonProperty("end")
  private Long end = null;

  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("organizationId")
  private UUID organizationId = null;

  @JsonProperty("query")
  private String query = null;

  @JsonProperty("relativePeriod")
  private Boolean relativePeriod = null;

  @JsonProperty("start")
  private Long start = null;

  @JsonProperty("updated")
  private LocalDateTime updated = null;

  @JsonProperty("userId")
  private UUID userId = null;

  public SavedSearch applicationIds(List<UUID> applicationIds) {
    this.applicationIds = applicationIds;
    return this;
  }

  public SavedSearch addApplicationIdsItem(UUID applicationIdsItem) {
    if (this.applicationIds == null) {
      this.applicationIds = new ArrayList<>();
    }
    this.applicationIds.add(applicationIdsItem);
    return this;
  }

   /**
   * Get applicationIds
   * @return applicationIds
  **/
  @ApiModelProperty(value = "")
  public List<UUID> getApplicationIds() {
    return applicationIds;
  }

  public void setApplicationIds(List<UUID> applicationIds) {
    this.applicationIds = applicationIds;
  }

  public SavedSearch created(LocalDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getCreated() {
    return created;
  }

  public void setCreated(LocalDateTime created) {
    this.created = created;
  }

  public SavedSearch end(Long end) {
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  @ApiModelProperty(value = "")
  public Long getEnd() {
    return end;
  }

  public void setEnd(Long end) {
    this.end = end;
  }

  public SavedSearch id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public SavedSearch name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SavedSearch organizationId(UUID organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @ApiModelProperty(value = "")
  public UUID getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(UUID organizationId) {
    this.organizationId = organizationId;
  }

  public SavedSearch query(String query) {
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @ApiModelProperty(value = "")
  public String getQuery() {
    return query;
  }

  public void setQuery(String query) {
    this.query = query;
  }

  public SavedSearch relativePeriod(Boolean relativePeriod) {
    this.relativePeriod = relativePeriod;
    return this;
  }

   /**
   * Get relativePeriod
   * @return relativePeriod
  **/
  @ApiModelProperty(value = "")
  public Boolean isRelativePeriod() {
    return relativePeriod;
  }

  public void setRelativePeriod(Boolean relativePeriod) {
    this.relativePeriod = relativePeriod;
  }

  public SavedSearch start(Long start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @ApiModelProperty(value = "")
  public Long getStart() {
    return start;
  }

  public void setStart(Long start) {
    this.start = start;
  }

  public SavedSearch updated(LocalDateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getUpdated() {
    return updated;
  }

  public void setUpdated(LocalDateTime updated) {
    this.updated = updated;
  }

  public SavedSearch userId(UUID userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public UUID getUserId() {
    return userId;
  }

  public void setUserId(UUID userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SavedSearch savedSearch = (SavedSearch) o;
    return Objects.equals(this.applicationIds, savedSearch.applicationIds) &&
        Objects.equals(this.created, savedSearch.created) &&
        Objects.equals(this.end, savedSearch.end) &&
        Objects.equals(this.id, savedSearch.id) &&
        Objects.equals(this.name, savedSearch.name) &&
        Objects.equals(this.organizationId, savedSearch.organizationId) &&
        Objects.equals(this.query, savedSearch.query) &&
        Objects.equals(this.relativePeriod, savedSearch.relativePeriod) &&
        Objects.equals(this.start, savedSearch.start) &&
        Objects.equals(this.updated, savedSearch.updated) &&
        Objects.equals(this.userId, savedSearch.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicationIds, created, end, id, name, organizationId, query, relativePeriod, start, updated, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SavedSearch {\n");
    
    sb.append("    applicationIds: ").append(toIndentedString(applicationIds)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    relativePeriod: ").append(toIndentedString(relativePeriod)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

