/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * TaxiiCollection
 */

public class TaxiiCollection {
  @JsonProperty("can_read")
  private Boolean canRead = null;

  @JsonProperty("can_write")
  private Boolean canWrite = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("media_types")
  private List<String> mediaTypes = null;

  @JsonProperty("title")
  private String title = null;

  public TaxiiCollection canRead(Boolean canRead) {
    this.canRead = canRead;
    return this;
  }

   /**
   * Get canRead
   * @return canRead
  **/
  @ApiModelProperty(value = "")
  public Boolean isCanRead() {
    return canRead;
  }

  public void setCanRead(Boolean canRead) {
    this.canRead = canRead;
  }

  public TaxiiCollection canWrite(Boolean canWrite) {
    this.canWrite = canWrite;
    return this;
  }

   /**
   * Get canWrite
   * @return canWrite
  **/
  @ApiModelProperty(value = "")
  public Boolean isCanWrite() {
    return canWrite;
  }

  public void setCanWrite(Boolean canWrite) {
    this.canWrite = canWrite;
  }

  public TaxiiCollection description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TaxiiCollection id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TaxiiCollection mediaTypes(List<String> mediaTypes) {
    this.mediaTypes = mediaTypes;
    return this;
  }

  public TaxiiCollection addMediaTypesItem(String mediaTypesItem) {
    if (this.mediaTypes == null) {
      this.mediaTypes = new ArrayList<>();
    }
    this.mediaTypes.add(mediaTypesItem);
    return this;
  }

   /**
   * Get mediaTypes
   * @return mediaTypes
  **/
  @ApiModelProperty(value = "")
  public List<String> getMediaTypes() {
    return mediaTypes;
  }

  public void setMediaTypes(List<String> mediaTypes) {
    this.mediaTypes = mediaTypes;
  }

  public TaxiiCollection title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaxiiCollection taxiiCollection = (TaxiiCollection) o;
    return Objects.equals(this.canRead, taxiiCollection.canRead) &&
        Objects.equals(this.canWrite, taxiiCollection.canWrite) &&
        Objects.equals(this.description, taxiiCollection.description) &&
        Objects.equals(this.id, taxiiCollection.id) &&
        Objects.equals(this.mediaTypes, taxiiCollection.mediaTypes) &&
        Objects.equals(this.title, taxiiCollection.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canRead, canWrite, description, id, mediaTypes, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaxiiCollection {\n");
    
    sb.append("    canRead: ").append(toIndentedString(canRead)).append("\n");
    sb.append("    canWrite: ").append(toIndentedString(canWrite)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    mediaTypes: ").append(toIndentedString(mediaTypes)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

